import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { mountWithApp } from "../../helpers/test-app-context";

const routerBack = vi.hoisted(() => vi.fn());

vi.mock("vue-router", () => ({
  useRouter: () => ({ back: routerBack }),
}));

const AgentDemoShellStub = {
  props: ["title", "subtitle"],
  emits: ["back"],
  template: `
    <div data-test="demo-shell">
      <span data-test="agent-demo-static-badge">Static example</span>
      <button data-test="shell-back" @click="$emit('back')">Back</button>
      <section data-test="shell-question"><slot name="question" /></section>
      <section data-test="shell-result"><slot name="result" /></section>
      <footer data-test="shell-footer"><slot name="footer" /></footer>
    </div>
  `,
};

const DeepGenomeArtifactStub = {
  props: {
    title: { type: String, default: "" },
    metadata: { type: [String, Array], default: "" },
    status: { type: String, default: "" },
    markdown: { type: String, default: "" },
    references: { type: Array, default: () => [] },
    ns: { type: String, default: "" },
  },
  template: `
    <article
      data-test="deep-genome-artifact"
      :data-title="title"
      :data-ns="ns"
      :data-markdown="markdown"
      :data-reference-count="references.length"
    >
      <div data-test="artifact-report">{{ markdown }}</div>
      <ol data-test="artifact-evidence">
        <li v-for="reference in references" :key="reference.file_id">
          {{ reference.title || reference.ti }}
        </li>
      </ol>
    </article>
  `,
};

const DeepGenomeResultViewerStub = {
  template: '<div data-test="legacy-deep-genome-viewer" />',
};

import DeepGenomeAgent from "@/views/deep-genome-agent/DeepGenomeAgentView.vue";

function mountDemo() {
  return mountWithApp(DeepGenomeAgent, {
    global: {
      stubs: {
        AgentDemoShell: AgentDemoShellStub,
        DeepGenomeArtifact: DeepGenomeArtifactStub,
        DeepGenomeResultViewer: DeepGenomeResultViewerStub,
      },
    },
  });
}

describe("Deep Genome Agent static demonstration", () => {
  it("keeps the exact scientific question, report, references, and namespace in one artifact", () => {
    const wrapper = mountDemo();

    const question = wrapper.get("[data-test=shell-question]").text();
    expect(question).toBe(
      "Please give me a scientifically rigorous and integrated account of the rice (Oryza sativa) gene Os01g0177400."
    );

    expect(wrapper.findAll("[data-test=deep-genome-artifact]")).toHaveLength(1);
    const artifact = wrapper.get("[data-test=deep-genome-artifact]");
    expect(artifact.attributes("data-ns")).toBe("deep-genome-demo");
    expect(artifact.attributes("data-reference-count")).toBe("256");
    expect(artifact.attributes("data-markdown")).toContain(
      "# Deep Genome Analysis of Os01g0177400"
    );
    expect(artifact.attributes("data-markdown")).toContain(
      "GA3ox-2|D18|GA3OX2"
    );
    expect(artifact.attributes("data-markdown")).toContain(
      "Os01t0177400-01_seed_101_sample_0.cif"
    );
    expect(artifact.attributes("data-markdown")).toContain("<sup>5</sup>");
    expect(artifact.attributes("data-markdown")).not.toContain(
      "[256] Physiological and Transcriptome Analyses"
    );
    expect(artifact.attributes("data-markdown")).not.toContain("## Reference:");
    expect(artifact.get("[data-test=artifact-evidence]").text()).toContain(
      "The rice YABBY1 gene is involved in the feedback regulation of gibberellin metabolism."
    );
    expect(artifact.get("[data-test=artifact-evidence]").text()).toContain(
      "Oryza sativa mediator subunit OsMED25 interacts with OsBZR1"
    );
  });

  it("keeps static disclosure, AI disclaimer, Back navigation, and no reaction persistence controls", async () => {
    routerBack.mockReset();
    const wrapper = mountDemo();
    const source = readFileSync(
      resolve(
        __dirname,
        "../../../src/views/deep-genome-agent/DeepGenomeAgentView.vue"
      ),
      "utf8"
    );

    expect(wrapper.get("[data-test=agent-demo-static-badge]").text()).toContain(
      "Static example"
    );
    expect(wrapper.get("[data-test=shell-footer]").text()).toContain(
      "Generated by AI. Please exercise discretion."
    );
    await wrapper.get("[data-test=shell-back]").trigger("click");
    expect(routerBack).toHaveBeenCalledTimes(1);

    expect(
      wrapper.findAll("[data-test=legacy-deep-genome-viewer]")
    ).toHaveLength(0);
    expect(
      wrapper.findAll(
        ".chat-header, .chat-messages, .message-avatar, .message-fotter"
      )
    ).toHaveLength(0);
    expect(
      wrapper.findAll('[class*="reaction"], [data-test*="reaction"]')
    ).toHaveLength(0);
    expect(source).not.toMatch(
      /loveThisState|needsImprovementState|handleReaction|localStorage/
    );
  });
});
