package api_service

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	rxBot "phytomni-server/external/bot"
	"phytomni-server/model"
)

// The public golden is generated by the real Go pipeline, not assembled as a
// browser payload. Its synthetic Bot inputs remain distinct from producer proof.
func TestReportIntegrityPublicProjectionGolden(t *testing.T) {
	gdb := setupTestDB(t)
	fixedTime := time.Date(2026, 9, 12, 0, 0, 0, 0, time.UTC)
	gdb.NowFunc = func() time.Time { return fixedTime }
	previousConfig := rxBot.BotConfig
	rxBot.BotConfig = nil
	t.Cleanup(func() { rxBot.BotConfig = previousConfig })
	service := NewService()
	ctx := context.Background()
	deepResult, err := os.ReadFile("testdata/report-integrity/deep-genome-failed-finalization.json")
	if err != nil {
		t.Fatal(err)
	}
	var deepCanonical struct {
		Formatted struct {
			Answer string `json:"answer"`
		} `json:"formatted"`
	}
	if err := json.Unmarshal(deepResult, &deepCanonical); err != nil {
		t.Fatal(err)
	}
	partial := deepCanonical.Formatted.Answer
	type producerInput struct {
		Agent    string          `json:"agent"`
		Scenario string          `json:"scenario"`
		Status   string          `json:"status"`
		Result   json.RawMessage `json:"result"`
	}
	terminalBytes, err := os.ReadFile("testdata/report-integrity/terminal-report-integrity.json")
	if err != nil {
		t.Fatal(err)
	}
	var terminalInputs []producerInput
	if err := json.Unmarshal(terminalBytes, &terminalInputs); err != nil {
		t.Fatal(err)
	}
	inputs := []struct {
		name, agent, status, query string
		result                     json.RawMessage
	}{
		{name: "partial-failed-deep-genome", agent: "deep_genome", status: "failed", query: "Synthetic expression evidence", result: deepResult},
	}
	for _, candidate := range terminalInputs {
		name := "empty-synthesis-archive-" + candidate.Agent
		if candidate.Scenario == "no_text" {
			name = "no-science-archive-" + candidate.Agent
		}
		inputs = append(inputs, struct {
			name, agent, status, query string
			result                     json.RawMessage
		}{name, candidate.Agent, candidate.Status, "Synthetic analysis archive", candidate.Result})
	}
	type publicCase struct {
		ID        string                  `json:"id"`
		History   *ConversationHistoryRow `json:"history"`
		Lifecycle AgentTaskLifecycleDTO   `json:"lifecycle"`
	}
	golden := struct {
		SchemaVersion    int          `json:"schema_version"`
		Provenance       string       `json:"provenance"`
		ProducerEvidence string       `json:"producer_evidence"`
		Cases            []publicCase `json:"cases"`
	}{
		SchemaVersion:    1,
		Provenance:       "Generated by TestReportIntegrityPublicProjectionGolden through DecodeRunProjection, applyBotRunProjection, persisted reload, AnswerCheck and AgentTaskLifecycle.",
		ProducerEvidence: "Byte-exact Bot serializer fixtures verified by test_report_integrity_contract.py and test_terminal_report_integrity_contract.py; synthetic science and delivery only.",
	}
	for index, input := range inputs {
		row := model.QuestionAgentLog{
			Id: int64(8001 + index), UserName: "synthetic-owner", DialogueId: input.name,
			BotRunId: "run-" + input.name, ToolName: slugToToolName[input.agent], Query: input.query,
			Status: "RUNNING", BotReportRevision: -1, CreatedAt: fixedTime, UpdatedAt: fixedTime,
		}
		if err := gdb.Create(&row).Error; err != nil {
			t.Fatal(err)
		}
		record := rxBot.RunRecord{RunID: row.BotRunId, Agent: input.agent, Status: input.status, Result: input.result}
		decoded, err := DecodeRunProjection(record)
		if err != nil {
			t.Fatal(err)
		}
		if err := service.applyBotRunProjection(ctx, &row, &record, rxBot.ResponseMeta{}); err != nil {
			t.Fatal(err)
		}
		persisted := loadBotRunProjectionForTest(t, row.UserName, row.Id)
		if persisted.VisibleReport() != decoded.VisibleReport() || !bytes.Equal(mustIntegrityJSON(t, persisted.Report), mustIntegrityJSON(t, decoded.Report)) {
			t.Fatal("decode/store report mismatch")
		}
		var before model.QuestionAgentLog
		if err := gdb.First(&before, row.Id).Error; err != nil {
			t.Fatal(err)
		}
		history, err := service.AnswerCheck(ctx, row.UserName, row.DialogueId)
		if err != nil || len(history) != 1 {
			t.Fatalf("history rows=%d err=%v", len(history), err)
		}
		lifecycle, err := service.AgentTaskLifecycle(ctx, row.Id, row.UserName)
		if err != nil {
			t.Fatal(err)
		}
		if input.agent == "deep_genome" {
			if persisted.VisibleReport() != partial || lifecycle.Phase != "FAILED" || !lifecycle.ArtifactSummary.HasReport || len(lifecycle.Children) != 0 || persisted.Progress.Completed != 12 {
				t.Fatalf("partial failed scientific state lost: same_text=%t phase=%s has_report=%t children=%d completed=%d progress=%+v", persisted.VisibleReport() == partial, lifecycle.Phase, lifecycle.ArtifactSummary.HasReport, len(lifecycle.Children), persisted.Progress.Completed, persisted.Progress)
			}
			var cited struct {
				Content    string           `json:"content"`
				References []map[string]any `json:"doc_list"`
			}
			if err := json.Unmarshal([]byte(history[0].Answer), &cited); err != nil {
				t.Fatal(err)
			}
			if cited.Content != partial || len(cited.References) != 1 || cited.References[0]["title"] != "Synthetic evidence" {
				t.Fatal("history bibliography lost")
			}
		} else if history[0].Answer != "" || lifecycle.Phase != "SUCCEEDED" || lifecycle.ArtifactSummary.HasReport || history[0].Delivery == nil || history[0].Delivery.Status != "ready" || len(history[0].Artifacts) != 1 || history[0].Artifacts[0].Kind != "archive" {
			t.Fatal("no-science report hid archive or changed execution")
		}
		var after model.QuestionAgentLog
		if err := gdb.First(&after, row.Id).Error; err != nil {
			t.Fatal(err)
		}
		if before.Answer != after.Answer || before.BotProjectionJSON != after.BotProjectionJSON || before.BotReportRevision != after.BotReportRevision {
			t.Fatal("history read mutated durable state")
		}
		golden.Cases = append(golden.Cases, publicCase{ID: input.name, History: history[0], Lifecycle: lifecycle})
	}
	encoded, err := json.MarshalIndent(golden, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	encoded = append(encoded, '\n')
	for _, forbidden := range []string{"obs://", "synthetic-bucket", "private_unknown", "private diagnostic", "inventory_digest", "archive_ref", "conversation_context", "synthetic-umbrella"} {
		if strings.Contains(string(encoded), forbidden) {
			t.Fatalf("public golden leaked %s", forbidden)
		}
	}
	const path = "../../../web/tests/fixtures/report-integrity/public-projection.json"
	if os.Getenv("PHYTOMNI_UPDATE_REPORT_GOLDEN") == "1" {
		if err := os.WriteFile(path, encoded, 0600); err != nil {
			t.Fatal(err)
		}
	}
	expected, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(expected, encoded) {
		t.Fatal("public projection golden differs; regenerate with PHYTOMNI_UPDATE_REPORT_GOLDEN=1 after reviewing pipeline changes")
	}
}

func mustIntegrityJSON(t *testing.T, value any) []byte {
	t.Helper()
	data, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return data
}
