/**
 * Sanitized real-content fixture derived from the shipped Deep Genome demo.
 * It keeps the report's scientific density and reference shape without using
 * authenticated responses, private identifiers, or external network assets.
 */
export const REAL_DEEP_GENOME_REFERENCES = [
  {
    file_id: "visual-real-reference-01",
    title:
      "The rice YABBY1 gene is involved in the feedback regulation of gibberellin metabolism.",
  },
  {
    file_id: "visual-real-reference-02",
    title: "Gibberellin 2-oxidase genes and uses thereof",
  },
  {
    file_id: "visual-real-reference-03",
    title:
      "Expression of novel rice gibberellin 2-oxidase gene is under homeostatic regulation by biologically active gibberellins.",
  },
  {
    file_id: "visual-real-reference-04",
    au: "Murai, M. et al",
    ti: "Pleiotropic effect of the dwarfing gene d18-k on cool tolerance at booting stage under the genetic background of an extremely cool-tolerant line Norin-PL8 in rice",
    so: "PLANT BREEDING",
    vl: "122",
    bp: "410",
    ep: "415",
    py: "2003",
    di: "10.1046/j.1439-0523.2003.00843.x",
    dl: "https://doi.org/10.1046/j.1439-0523.2003.00843.x",
  },
  {
    file_id: "visual-real-reference-05",
    title:
      "Expression of a gibberellin 2-oxidase gene around the shoot apex is related to phase transition in rice",
  },
  {
    file_id: "visual-real-reference-06",
    au: "Shukla, N. et al",
    ti: "Biochemical and physiological responses of rice (Oryza sativa L.) as influenced by Trichoderma harzianum under drought stress",
    so: "PLANT PHYSIOLOGY AND BIOCHEMISTRY",
    vl: "54",
    bp: "78",
    ep: "88",
    py: "2012",
    di: "10.1016/j.plaphy.2012.02.001",
    dl: "https://doi.org/10.1016/j.plaphy.2012.02.001",
  },
  {
    file_id: "visual-real-reference-07",
    title:
      "Hd18, encoding histone acetylase related to Arabidopsis FLOWERING LOCUS D, is involved in the control of flowering time in rice",
  },
  {
    file_id: "visual-real-reference-08",
    title:
      "Oryza sativa mediator subunit OsMED25 interacts with OsBZR1 to regulate brassinosteroid signaling and plant architecture in rice",
  },
];

export const REAL_DEEP_GENOME_MARKDOWN = [
  "# Deep Genome Analysis of Os01g0177400",
  "",
  "GA3ox-2|D18|GA3OX2|dwf15|OsGA3ox-2|d18h|GA3ox1|d18-k|d18-I|ga3ox2|d18|OsGA3ox2|d18-h|OsGA3OX2|d18-dy|d18-AD|d25|Os01g0177400 in rice (Oryza sativa) encodes a gibberellin 3-beta-hydroxylase, a crucial enzyme in the biosynthesis of gibberellins. This gene converts GA20 and GA9 to the bioactive forms GA1 and GA4, playing a pivotal role in the final step of gibberellin biosynthesis [1][2][3].",
  "",
  "Genetic mapping localized GA3ox-2/D18 to chromosome 1, associating it with dwarfism and gibberellin biosynthesis pathways. Its alleles show pleiotropic effects on plant height, cool tolerance, and stress responses, while map-based cloning revealed three exons and two introns with conserved domains typical of 2-oxoglutarate-dependent dioxygenases [1][4][5].",
  "",
  "## Gene Profiles",
  "",
  "### 1. Gene Discovery, Family, and Localization",
  "",
  "#### 1.1. Discovery History and Nomenclature",
  "",
  "The aliases GA3ox-2, D18, GA3OX2, dwf15, OsGA3ox-2, d18h, GA3ox1, d18-k, d18-I, ga3ox2, d18, OsGA3ox2, d18-h, OsGA3OX2, d18-dy, d18-AD, d25, and Os01g0177400 collectively refer to the gibberellin 3-beta-hydroxylase gene in rice. The gene converts GA20 and GA9 to bioactive GA1 and GA4, linking hormone homeostasis to plant stature and breeding outcomes [1][2][3].",
  "",
  "#### 1.2. Genetic Mapping",
  "",
  "The gene is located on chromosome 1 in a region associated with dwarfism and gibberellin biosynthesis. Quantitative trait locus studies identify it as a major contributor to plant height, cool tolerance, and stress response [2][4].",
  "",
  "### 2. Gene Cloning and Structural Analysis",
  "",
  "#### 2.1. Cloning Information",
  "",
  "Map-based cloning isolated the genomic region responsible for the dwarf phenotype and clarified the regulatory role of GA3ox-2/D18 in rice growth [1][3].",
  "",
  "#### 2.2. Structural Characteristics",
  "",
  "The coding sequence contains conserved 2OG-Fe(II) oxygenase features, including a non-haem dioxygenase N-terminal domain and an isopenicillin N synthase-like catalytic domain [1][5].",
  "",
  "## Functional Analysis",
  "",
  "### 3.1. Expression Patterns",
  "",
  "GA3ox-2/D18 is expressed in leaves, flowers, and seeds, with levels shaped by developmental stage and environmental conditions. Flower tissue shows the highest representative transcript abundance, while meristem tissue shows the lowest [3][5].",
  "",
  "### 3.2. Phenotypic Characteristics and Biological Functions",
  "",
  "Mutants exhibit dwarfism, reduced plant height, and altered gibberellin levels. These alleles contributed to semi-dwarf rice varieties that reduce lodging and improve grain yield [1][2][4].",
  "",
  "### 3.3. Pathways and Networks",
  "",
  "GA3ox-2/D18 converts precursors to active gibberellins and interacts with GA20ox and GA2ox to maintain hormone balance. The pathway is modulated by feedback mechanisms that couple gene activity to growth and stress responses [1][6].",
  "",
  "## Application and Evolutionary Analysis",
  "",
  "### 4.1. Domestication Studies",
  "",
  "The gene has been a breeding target for semi-dwarf varieties that combine improved yield with reduced lodging. Natural alleles contribute to diversity in plant height and environmental adaptability [2][4].",
  "",
  "**Table: Key mutations in the GA3ox-2/D18 gene and their phenotypic effects**",
  "",
  "| Allele | Background cultivar | Phenotypic effect | Molecular basis | Reference(s) |",
  "| --- | --- | --- | --- | --- |",
  "| d18-AD | Akibare | Severe dwarfism, GA-responsive | 7-kbp deletion encompassing the gene | [7] |",
  "| d18-dy | Waito-C | Milder dwarfism | In-frame 9-base deletion in exon 1 | [7][8] |",
  "| d18-h | Nosetsu-waisei | Severe dwarfism, loss of enzyme activity | Frameshift and premature stop | [8] |",
  "| d18-k | Kotaketamanishiki | Dwarfism with cool tolerance | Molecular basis not fully characterized | [1] |",
  "",
  "### 4.2. Representative expression figure",
  "",
  "![Representative rice gene expression figure](/logo.png)",
  "",
  "## Bioinformatic Analysis and Molecular Design",
  "",
  "### 5.1. Phylogenetic Analysis",
  "",
  "The phylogenetic analysis resolves multiple monophyletic clades with strong support. Conserved homologs cluster around the 2OG-Fe(II) oxygenase superfamily, supporting the proposed catalytic role of the protein.",
  "",
  "### 5.2. Protein Characterization",
  "",
  "The protein contains a 2OG-FeII_Oxy domain and a DIOX_N domain, with highly significant matches that are consistent with a non-haem dioxygenase architecture.",
  "",
  "## Conclusion",
  "",
  "GA3ox-2/D18 in rice is pivotal in gibberellin biosynthesis and plant growth regulation. Its allelic diversity, expression profile, and role in hormone homeostasis make it a useful target for crop improvement and future stress-response research [1][2][3][4].",
].join("\n");
