package common

import (
	"github.com/gin-gonic/gin"
)

const (
	// A2uiGatewayErrorType is the stable discriminator for errors generated by
	// the Web A2UI gateway. Bot response bodies are never adapted to this shape.
	A2uiGatewayErrorType = "gateway_error"
	// A2uiRequestIDMaxChars bounds the correlation identifier copied into a
	// client-visible local error envelope.
	A2uiRequestIDMaxChars = 256
)

type A2uiHTTPError struct {
	Error struct {
		Type      string `json:"type"`
		Code      string `json:"code"`
		Message   string `json:"message"`
		RequestID string `json:"request_id"`
	} `json:"error"`
	Forwarded bool `json:"forwarded"`
	Retryable bool `json:"retryable"`
}

func NewA2uiHTTPError(
	code string,
	message string,
	requestID string,
	forwarded bool,
	retryable bool,
) A2uiHTTPError {
	requestID = boundA2uiRequestID(requestID)
	var envelope A2uiHTTPError
	envelope.Error.Type = A2uiGatewayErrorType
	envelope.Error.Code = code
	envelope.Error.Message = message
	envelope.Error.RequestID = requestID
	envelope.Forwarded = forwarded
	envelope.Retryable = retryable
	return envelope
}

// A2uiRequestID reads only the request-id value established in Gin context by
// the request-id middleware. In particular, it does not fall back to the raw
// incoming header, which could bypass upstream length validation.
func A2uiRequestID(c *gin.Context) string {
	if c == nil {
		return ""
	}
	value, exists := c.Get("x-request-id")
	if !exists {
		return ""
	}
	id, ok := value.(string)
	if !ok {
		return ""
	}
	return boundA2uiRequestID(id)
}

// WriteA2uiHTTPError writes the common local envelope without exposing the
// service, database, or upstream error text to the caller.
func WriteA2uiHTTPError(
	c *gin.Context,
	status int,
	code string,
	message string,
	forwarded bool,
	retryable bool,
) {
	if c == nil {
		return
	}
	c.JSON(status, NewA2uiHTTPError(code, message, A2uiRequestID(c), forwarded, retryable))
}

func boundA2uiRequestID(id string) string {
	runes := []rune(id)
	if len(runes) <= A2uiRequestIDMaxChars {
		return id
	}
	return string(runes[:A2uiRequestIDMaxChars])
}
