/*
 * 组件注释
 * @Author: AI Assistant
 * @Date: 2024-06-17
 * @Description: English language pack
 * 既往不恋！当下不杂！！未来不迎！！！
 */
export default {
  // Common parts
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    success: 'Success',
    failed: 'Failed',
    warning: 'Warning',
    info: 'Information',
    loading: 'Loading',
    noData: 'No Data',
    save: 'Save',
    reset: 'Reset',
    back: 'Back',
    more: 'More',
    submit: 'Submit',
    close: 'Close',
    view: 'View',
    index: 'No.',
    operation: 'Operation',
    running:'Running',
    waiting:'Waiting',
    finished:"Finished",
    Tip:"(Generated by AI)",
    aiDisclaimer: 'Generated by AI. Please exercise discretion.'
  },

  // App information
  app: {
    title: 'CAAS Breeding Large Model Intelligence Platform',
  },

  // Interactive Tutorial
  tutorial: {
    step1: {
      title: 'Welcome to Phytomni!',
      content: 'First, let\'s get to know the navigation. Quick access to functions: "Start New" initiates a brand-new task, "Gene Display" allows you to view gene displays, "Favorites" is for collecting frequently-used content, and there are also historical interactions categorized by time to help you efficiently find past records.',
      button: 'Click "Next Step" to continue exploring!'
    },
    step2: {
      title: 'Agent Demos',
      content: 'These buttons at the bottom are demos of different agents. You can click to view specific usage cases.',
      button: 'Click "Next Step" to learn about the conversation area.'
    },
    step3: {
      title: 'Conversation Window',
      content: 'This is the "window" for communicating with Phytomni. You can directly enter questions, or choose different intelligent assistants such as "ChatAgent" and "KnowledgeAgent" by yourself. Try clicking the input box. Are you ready to start exploring?',
      button: 'Click "Complete" to end the guidance!'
    },
    nextStep: 'Next Step',
    prevStep: 'Previous',
    complete: 'Complete',
    skip: 'Skip Tutorial',
    startTutorial: 'Start Tutorial',
    restartTutorial: 'Restart Tutorial',
    navigationHint: '💡 Tip: Use ← → arrow keys or spacebar to navigate, ESC to exit'
  },

  // Menu
  menu: {
    geneDisplay: 'Gene Display',
    favorites: 'Favorites',
    feedback: 'Feedback',
    userList: 'User List',
    logList: 'System Monitor',
    permissionManage: 'Permissions',
    taskManager:'Task Management',
    globalConfig: 'Global Policy Config',
    adminManagement: 'Admin Management'
  },

  // Error codes
  errorCode: {
    401: 'Authentication failed, unable to access system resources',
    403: 'Current operation is not authorized',
    404: 'Requested resource does not exist',
    default: 'Unknown system error, please report to administrator',
  },

  // Change password
  changePassword: {
    usernamePlaceholder: 'Please enter username',
    oldPassword: 'Old Password',
    oldPasswordPlaceholder: 'Please enter old password',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Please enter new password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Please confirm new password',
    confirm: 'Confirm Change',
    success: 'Password changed successfully!',
    usernameRequired: 'Please enter username',
    oldPasswordRequired: 'Please enter old password',
    newPasswordRequired: 'Please enter new password',
    confirmPasswordRequired: 'Please confirm new password',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordMinLength8: 'Password must be at least 8 characters',
    passwordNeedUppercase: 'Password must contain uppercase letters',
    passwordNeedLowercase: 'Password must contain lowercase letters',
    passwordNeedNumber: 'Password must contain numbers',
    passwordNeedSpecial: 'Password must contain special characters',
    passwordSame: 'New password cannot be the same as old password',
    passwordMismatch: 'Passwords do not match',
    formValidationFailed: 'Please check the form for errors'
  },

  // Login module
  login: {
    title: 'Phytomni',
    subtitle: 'A multi-agent system for scientific discovery and plant design',
    registerTitle: 'Register for Breeding Intelligence Platform',
    email: 'Email',
    emailPlaceholder: 'Please enter your email address',
    password: 'Password',
    passwordPlaceholder: '8-16 characters, case sensitive',
    forgotPassword: 'Forgot password?',
    loginButton: 'Login',
    registerButton: 'Register',
    noAccount: 'No account?',
    hasAccount: 'Already have an account?',
    register: 'Register',
    login: 'Login',
    loginSuccess: 'Login successful',
    registerSuccess: 'Registration successful',
    loginFailed: 'Login failed',
    registerFailed: 'Registration failed',
    passwordWarningTitle: 'Password Security Notice',
    accountLockedTitle: 'Account Locked',
    accountLockedMessage: 'Your account has been locked for {minutes} minutes due to multiple failed login attempts. Please try again later.',
    remainingAttempts: 'Login failed. You have {count} attempts remaining',
    firstLoginTitle: 'First Login Notice',
    firstLoginMessage: 'This is your first login. For security purposes, please change your initial password.',
    slogan: {
      main: 'Life Science Foundation Model',
      sub: 'Decoding Life',
    },
    validation: {
      emailRequired: 'Please enter your email',
      emailFormat: 'Please enter a valid email address',
      passwordRequired: 'Please enter your password',
      passwordLength: 'Password must be 8-16 characters long',
    },
    agreement: {
      prefix: 'Registering and logging in means you have read and agreed to our',
      terms: 'User Agreement',
      and: 'and',
      privacy: 'Privacy Policy',
    },
  },

  // Register module
  register: {
    title: 'Create Account',
    subtitle: 'Create your Phytomni account',
    email: 'Email',
    emailPlaceholder: 'Please enter your email address',
    password: 'Password',
    passwordPlaceholder: 'Please enter your password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Please confirm your password',
    registerButton: 'Register',
    haveAccount: 'Already have an account?',
    login: 'Login',
    agreement: {
      prefix: 'By registering, you agree to our',
      terms: 'Terms of Service',
      and: 'and',
      privacy: 'Privacy Policy',
    },
    validation: {
      emailRequired: 'Please enter your email address',
      emailFormat: 'Please enter a valid email address',
      passwordRequired: 'Please enter your password',
      passwordLength: 'Password must be 8-16 characters long',
      passwordMinLength8: 'Password must be at least 8 characters',
      passwordMaxLength16: 'Password must not exceed 16 characters',
      passwordNeedUppercase: 'Password must contain uppercase letters',
      passwordNeedLowercase: 'Password must contain lowercase letters',
      passwordNeedNumber: 'Password must contain numbers',
      passwordNeedSpecial: 'Password must contain special characters',
      confirmPasswordRequired: 'Please confirm your password',
      confirmPasswordMismatch: 'Passwords do not match',
      formValidationFailed: 'Please check the form for errors'
    }
  },

  // Forgot password module
  forgotPassword: {
    title: 'Forgot Password',
    subtitle: 'Reset your account password',
    email: 'Email',
    emailPlaceholder: 'Please enter your registered email address',
    verificationCode: 'Verification Code',
    codePlaceholder: 'Please enter the verification code',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Please enter your new password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Please confirm your new password',
    sendResetEmail: 'Send Reset Email',
    verifyCode: 'Verify Code',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    successTitle: 'Password Reset Successful',
    successMessage: 'Your password has been successfully reset. Please login with your new password.',
    unavailableTitle: 'Password Reset Not Yet Available',
    unavailableMessage: 'This feature is under development. Please contact your system administrator to reset your password.',
    agreement: {
      prefix: 'By resetting your password, you agree to our',
      terms: 'Terms of Service',
      and: 'and',
      privacy: 'Privacy Policy',
    },
    validation: {
      emailRequired: 'Please enter your email address',
      emailFormat: 'Please enter a valid email address',
      codeRequired: 'Please enter the verification code',
      codeLength: 'Verification code must be 4-6 digits',
      passwordRequired: 'Please enter your new password',
      passwordLength: 'Password must be 8-16 characters long',
      confirmPasswordRequired: 'Please confirm your new password',
      confirmPasswordMismatch: 'Passwords do not match',
    },
  },

  // User management
  user: {
    list: 'User List',
    add: 'Add User',
    edit: 'Edit User',
    username: 'Username',
    password: 'Password',
    role: 'Role',
    roleSelect: 'Please select a role',
    superAdmin: 'Super Admin',
    admin: 'Administrator',
    normalUser: 'Normal User',
    addSuccess: 'Added successfully',
    editSuccess: 'Edited successfully',
    addFailed: 'Add failed',
    editFailed: 'Edit failed',
    detail: 'User Details',
    changePassword: 'Change Password',
    feedback: 'Feedback',
    logout: 'Logout',
    history: 'History',
    profile: 'Profile',
    cloudStorage: 'Cloud Storage',
    systemMonitor: 'System Monitor',
    globalConfig: 'Global Policy Config',
    adminManagement: 'Admin Management',
    unlock: 'Unlock',
    unlockConfirmTitle: 'Unlock User',
    unlockConfirmMessage: 'Are you sure you want to unlock user {email}?',
    unlockSuccess: 'User unlocked successfully',
    unlockFailed: 'Failed to unlock user',
    phone: 'Phone',
    phonePlaceholder: 'Please enter phone number',
    organization: 'Organization',
    organizationPlaceholder: 'Please enter organization',
    position: 'Position',
    positionPlaceholder: 'Please enter position',
    lastLoginAt: 'Last Login',
    notLoggedIn: 'Not logged in',
    chatLimit: 'Chat Limit',
    chatLimitPlaceholder: 'Please enter chat limit',
    unlimited: 'Unlimited',
    validation: {
      emailRequired: 'Please enter username',
      emailFormat: 'Please enter a valid email address',
      passwordRequired: 'Please enter password',
      passwordLength: 'Length must be between 8 and 16 characters',
      passwordMinLength8: 'Password must be at least 8 characters',
      passwordMaxLength16: 'Password must not exceed 16 characters',
      passwordNeedUppercase: 'Password must contain uppercase letters',
      passwordNeedLowercase: 'Password must contain lowercase letters',
      passwordNeedNumber: 'Password must contain numbers',
      passwordNeedSpecial: 'Password must contain special characters',
      roleRequired: 'Please select a role',
      formValidationFailed: 'Please check the form for errors'
    },
    logs: {
      formValidationFailed: 'Form validation failed',
    },
  },

  // Gene display
  gene: {
    title: 'Gene Details',
    id: 'ID',
    loadFailed: 'Failed to load',
    summary: 'Summary',
    details: 'Detailed Content',
    notFound: 'Gene details not found',
    searchPlaceholder: 'Please enter biocode to search',
    getFailed: 'Failed to get gene details',
    geneName: 'File Name',
    description: 'Description',
    synopsis: 'Synopsis',
    biocode: 'Biocode',
    geneId: 'Gene ID',
    picture: 'Picture',
    logs: {
      fetchDataFailed: 'Failed to fetch data:',
      fetchDetailFailed: 'Failed to fetch gene details:',
    },
  },

  // Chat module
  chat: {
    title: 'HELP',
    appTitle: 'Phytomni',
    welcome: 'Welcome, please enter your question directly',
    inputPlaceholder: 'Please enter your question...',
    send: 'Send',
    detailInfo: 'Detailed Information',
    relatedLinks: 'Related Links',
    newChat: 'Start New',
    exploreAgent: 'Explore Agents',
    exploreAgentCases: 'Explore Agent Cases',
    knowledgeBase: 'Knowledge',
    geneDetail: 'Gene Display',
    thinkingSteps: 'Thinking Steps',
    useTool: 'Use Tool',
    stepResult: 'Step Result',
    finalAnswer: 'Final Answer',
    sendFailed: 'Failed to send message, please try again later.',
    generationStopped: 'Generation stopped',
    relatedDocuments: 'Reference Material',
    welcomeTitle:"Hi, I'm Phytomni. Great to meet you!",
    welcomeSubtitle:"I can retrieve information and perform automated analysis for you. Feel free to give me your tasks.",
    inputPlaceholderTip: 'Please enter your question',
    uploadFile: 'Support file upload(max 10, accept .pdf,.doc,.xlsx,.ppt,.txt,.png)',
    noPermission: 'You do not have permission to use this model',
      timeGroup: {
      today: 'Today',
      yesterday: 'Yesterday',
      week: 'Within 7 Days',
      older: 'Older Than a Week',
    },
    features: {
      title: 'You can use, we provide',
      research: 'Deep Research',
      analysis: 'Biological Analysis',
      knowledge: 'Knowledge Retrieval',
      design: 'Data Design',
      organize: 'Data Organization',
      assistant: 'Experiment Assistant',
    },
    agents: {
      title: 'Intelligent Agents',
      description: 'Description',
      capabilities: 'Core Capabilities',
      usage: 'Usage Guide',
      RAG: 'RAG',
      BI: 'BI',
      GA: 'GA',
      search: 'Search',
      geneFunction: 'Gene Function Agent',
      review: 'Review Agent',
      chatAgent: 'Your AI assistant for answering plant research questions in natural language.',
      knowledgeAgent: 'Expert-curated plant knowledge at your fingertips.',
      dataAgent: 'Handles and optimizes plant datasets for research.',
      analystAgent: 'Transforms raw data into meaningful plant insights.',
      reviewAgent: 'Generates AI-powered literature reviews for agricultural research.',
      deepGenomeAgent: 'Decodes plant genomes for smarter breeding strategies.',
      inSilicoResearchAgent: 'Simulates plant experiments digitally to accelerate discovery.',
      geneNetworkAgent: 'Decodes gene regulatory networks to uncover key pathways for crop stress resistance and yield.',
      digitalDesignAgent: 'AI-driven design of gene promoters and protein structures for synthetic biology and molecular breeding.',
    },
    suggestions: {
      brca1:
        'What is the incidence rate of breast cancer caused by BRCA1 gene mutation?',
      mapk: 'What are the roles of MAPK signaling pathway in cell growth and differentiation?',
      tp53: 'What diseases can be caused by TP53 gene mutation?',
    },
    links: {
      brca1: 'BRCA1 Gene and Breast Cancer Research',
      mapk: 'MAPK Signaling Pathway Details',
      tp53: 'TP53 Gene Database',
    },
    logs: {
      openChatAgent: 'Open Chat Agent',
      openKnowledgeAgent: 'Open Knowledge Agent',
      openDatabaseAgent: 'Open Database Agent',
      openAnalysisAgent: 'Open Analysis Agent',
      openGeneFunctionAgent: 'Open Gene Function Agent',
      openReviewAgent: 'Open Review Agent',
      openKnowledgeBase: 'Open Knowledge Base',
      sendMessageFailed: 'Failed to send message:',
    },
    downloadURL:'Download link',
    copySuccess:'Copied successfully',
    copyFailed:"Copy failed",
    copy:'Copy',
    ladingInner:'Processing your request: retrieving data, analyzing information, and generating a response. Please wait',
    footer:'Generated by AI. Please carefully examine.',
    followUpQuestions: 'Question Suggestions:',
    more: 'More',
    actions: {
      rename: 'Rename',
      favorite: 'Favorite',
      unfavorite: 'Unfavorite',
      delete: 'Delete',
      deleteConfirm: 'Confirm Delete',
      deleteWarning: 'Are you sure you want to delete this conversation? This action cannot be undone.',
      enterNewTitle: 'Please enter a new title',
      titleRequired: 'Title is required',
    },
    favorites: 'Favorites',
    favoritesDescription: 'Manage your favorite conversations and quickly access important content',
    noFavorites: 'No Favorites',
    noFavoritesDescription: 'You haven\'t favorited any conversations yet. Start chatting and favorite the content you like',
    startChat: 'Start Chat',
    favoritesCount: '{count} Favorites',
    openChat: 'Open Chat',
    refresh: 'Refresh',
    regenerate: 'Regenerate',
    loveThis: 'Love this',
    needsImprovement: 'Needs Improvement',
    attachment: 'Attachment',
    hideLog: 'Hide Log',
    showLog: 'View Log',
    downloadFile: 'Download File',
  },

  // History module
  history: {
    noHistory: 'No history yet',
    noHistoryDescription: 'You don\'t have any chat history yet. Start chatting and view your conversation history',
    historyCount: '{count} history records',
  },

  // Profile management module
  profile: {
    title: 'Profile Management',
    description: 'Manage your personal information, account security and usage statistics',
    basicInfo: {
      title: 'Basic Information',
      username: 'Username',
      email: 'Email',
      phone: 'Phone',
      organization: 'Organization',
      position: 'Position',
    },
    security: {
      title: 'Account Security',
      password: 'Login Password',
      passwordDescription: 'Change your password regularly to ensure account security',
      changePassword: 'Change Password',
      permission: 'User Permission',
      permissionDescription: 'Current account permission level',
      oldPassword: 'Old Password',
      oldPasswordPlaceholder: 'Please enter old password',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Please enter new password',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Please confirm new password',
    },
    usage: {
      title: 'Usage Statistics',
      totalChats: 'Total Chats',
      totalFiles: 'Total Files',
      storageUsed: 'Storage Used',
      lastLogin: 'Last Login',
    },
  },

  // Cloud storage module
  cloudStorage: {
    tryDemo: 'Try Demo',
    totalFiles: 'Total Files',
    usedStorage: 'Used Storage',
    availableStorage: 'Available Storage',
    usagePercentage: 'Usage Rate',
    storageUsage: 'Storage Usage',
    uploadFiles: 'Upload Files',
    createFolder: 'Create Folder',
    searchPlaceholder: 'Search files or folders...',
    viewMode: {
      list: 'List View',
      grid: 'Grid View',
    },
    noFiles: 'No files yet',
    noFilesDescription: 'Current folder is empty. Upload your first file or create a folder to get started',
    uploadFirstFile: 'Upload First File',
    folderName: 'Folder Name',
    folderNamePlaceholder: 'Please enter folder name',
    newName: 'New Name',
    newNamePlaceholder: 'Please enter new name',
    actions: {
      download: 'Download',
      rename: 'Rename',
      move: 'Move',
      share: 'Share',
      delete: 'Delete',
      deleteConfirm: 'Confirm Delete',
      deleteWarning: 'Are you sure you want to delete this file? This action cannot be undone.',
    },
  },

  // Log management
  log: {
    list: 'Log List',
  },

  // Permission management
  permission: {
    title: 'Permissions',
  },

  // Pagination
  pagination: {
    total: 'Total {total} items',
    jump: 'Go to',
    page: 'Page',
    item: 'items/page',
    items: 'items',
  },
   // 任务管理
  taskManager:{
    question:'Question',
    status:"Status",
    updated_at:'Updated Time',
    downloadURL:'Download',
    dialogue_link:'Link',
    getFailed: 'Failed to get list',
    logs:{
      fetchDataFailed:'Failed to obtain data list'
    },
         operate:'Operate',
   },

  // User Feedback
  feedback: {
    title: 'User Feedback',
    description: 'We value your opinions and suggestions. Please let us know what you think',
    placeholder: 'Please describe your questions, suggestions, or feedback in detail...',
    submit: 'Submit Feedback',
    submitSuccess: 'Feedback submitted successfully. Thank you for your valuable input!',
    submitFailed: 'Submission failed, please try again',
  },

  // Global Policy Configuration
  globalConfig: {
    description: 'Manage system global policies and security configurations',
    systemSettings: 'System Settings',
    basicSettings: 'Basic Configuration',
    securitySettings: 'Security Policy',
    featureSettings: 'Feature Configuration',
    systemName: 'System Name',
    systemNamePlaceholder: 'Please enter system name',
    maxFileSize: 'Max File Size',
    sessionTimeout: 'Session Timeout',
    minutes: 'minutes',
    passwordPolicy: 'Password Policy',
    requireUppercase: 'Require Uppercase',
    requireLowercase: 'Require Lowercase',
    requireNumbers: 'Require Numbers',
    requireSymbols: 'Require Symbols',
    loginAttempts: 'Max Login Attempts',
    attempts: 'attempts',
    ipWhitelist: 'IP Whitelist',
    ipWhitelistPlaceholder: 'Please enter IP addresses, one per line',
    enableRegistration: 'Enable User Registration',
    enableFileUpload: 'Enable File Upload',
    enableChatHistory: 'Enable Chat History',
    maxChatHistory: 'Max Chat History Records',
    records: 'records',
    testConfig: 'Test Configuration',
    configHistory: 'Configuration History',
    timestamp: 'Timestamp',
    operator: 'Operator',
    changes: 'Changes',
    historyDetail: 'History Detail',
    saveSuccess: 'Configuration saved successfully',
    saveFailed: 'Failed to save configuration',
    resetConfirm: 'Are you sure you want to reset all configurations to default values?',
    resetSuccess: 'Configuration reset successfully',
    testSuccess: 'Configuration test passed',
    testFailed: 'Configuration test failed',
  },

  // Agent Pages
  agents: {
    analyst: {
      title: 'Analyst Agent',
      subtitle: 'Analysis Agent - Provides bioinformatics data analysis and interpretation services'
    },
    data: {
      title: 'Data Agent', 
      subtitle: 'Data Agent - Provides multi-omics data analysis and processing services'
    },
    briefReview: {
      title: 'Brief Review Agent',
      subtitle: 'Brief Review Agent - Provides rapid review and summary services for research topics'
    },
    knowledge: {
      title: 'Knowledge Agent',
      subtitle: 'Knowledge Agent - Provides bioinformatics knowledge query and analysis services'
    },
    deepGenome: {
      title: 'Deep Genome Agent',
      subtitle: 'Deep Genome Agent - Provides in-depth analysis services for species and genes',
      taskCreated: 'Task created successfully'
    },
    geneNetwork: {
      title: 'Gene Network Agent',
      subtitle: 'Gene Network Agent - Provides gene network analysis and phenotype trait association services'
    },
    digitalDesign: {
      title: 'Digital Design Agent',
      subtitle: 'Digital Design Agent - Provides protein structure prediction and design services based on gene IDs'
    }
  },

  // Help Center
  help: {
    title: 'Help Center',
    subtitle: 'Phytomni User Guide and Feature Documentation',
    quickStart: {
      title: 'Quick Start',
      step1: {
        title: 'Login to System',
        description: 'Use your email and password to login to the Phytomni platform'
      },
      step2: {
        title: 'Start Conversation',
        description: 'Enter your questions in the chat interface, AI assistant will provide professional answers'
      },
      step3: {
        title: 'Upload Files',
        description: 'Support uploading PDF, Word, Excel and other format files for analysis'
      },
      step4: {
        title: 'Use Intelligent Agents',
        description: 'Select different professional agents to assist you with specific tasks'
      }
    },
    features: {
      title: 'Core Features',
      research: {
        title: 'Deep Research',
        description: 'Conduct in-depth research analysis based on massive literature and databases',
        item1: 'Literature Search and Review',
        item2: 'Research Trend Analysis',
        item3: 'Expert Knowledge Integration'
      },
      analysis: {
        title: 'Biological Analysis',
        description: 'Professional bioinformatics analysis tools and algorithms',
        item1: 'Gene Function Analysis',
        item2: 'Protein Structure Prediction',
        item3: 'Metabolic Pathway Analysis'
      },
      design: {
        title: 'Data Design',
        description: 'Intelligent experimental design and data analysis solutions',
        item1: 'Experimental Design',
        item2: 'Data Visualization',
        item3: 'Result Interpretation and Suggestions'
      }
    },
    agents: {
      title: 'Intelligent Agents',
      capabilities: 'Core Capabilities',
      usage: 'Usage Guide',
      chat: {
        name: 'Chat Agent',
        description: 'Your AI assistant for answering plant science research questions in natural language',
        capability1: 'Natural Language Understanding',
        capability2: 'Multi-turn Conversation',
        capability3: 'Context Memory',
        usage: 'Directly input questions to get professional answers and suggestions'
      },
      knowledge: {
        name: 'Knowledge Agent',
        description: 'Provides authoritative plant science knowledge base and literature search',
        capability1: 'Knowledge Retrieval',
        capability2: 'Literature Analysis',
        capability3: 'Expert Knowledge Integration',
        usage: 'Query professional knowledge and latest research progress in specific fields'
      },
      data: {
        name: 'Data Agent',
        description: 'Process and analyze various types of plant-related data',
        capability1: 'Data Processing',
        capability2: 'Statistical Analysis',
        capability3: 'Result Visualization',
        usage: 'Upload data files to get professional analysis results and charts'
      },
      analysis: {
        name: 'Analysis Agent',
        description: 'Provides in-depth bioinformatics analysis services',
        capability1: 'Gene Analysis',
        capability2: 'Protein Analysis',
        capability3: 'Metabolic Analysis',
        usage: 'Input gene sequences or protein information to get detailed functional analysis'
      }
    },
    tips: {
      title: 'Usage Tips',
      question: {
        title: 'Question Techniques',
        description: 'Use specific and clear question descriptions to get more accurate answers'
      },
      upload: {
        title: 'File Upload',
        description: 'Supports multiple file formats, recommended file size not exceeding 10MB'
      },
      followup: {
        title: 'Follow-up Questions',
        description: 'Based on AI responses, you can continue to ask in-depth questions for more detailed information'
      },
      save: {
        title: 'Save Conversations',
        description: 'Important conversations can be favorited and saved for future viewing and sharing'
      }
    },
    faq: {
      title: 'Frequently Asked Questions',
      q1: {
        question: 'How to get more accurate answers?',
        answer: 'We recommend providing specific and detailed question descriptions, including relevant background information and specific needs. You can also upload relevant documents or data files to get more precise analysis results.'
      },
      q2: {
        question: 'What file formats are supported?',
        answer: 'We support common file formats such as PDF, Word, Excel, PowerPoint, TXT, PNG, etc. Individual file size is recommended not to exceed 10MB.'
      },
      q3: {
        question: 'How to choose the right intelligent agent?',
        answer: 'Choose based on your specific needs: Chat Agent for general Q&A, Knowledge Agent for literature search, Data Agent for data analysis, Analysis Agent for bioinformatics analysis.'
      },
      q4: {
        question: 'How is data security guaranteed?',
        answer: 'We adopt enterprise-level security measures to protect your data, including data encryption, access control, regular backups, etc., to ensure your data security and privacy protection.'
      }
    },
    contact: {
      title: 'Contact Us',
      email: 'Technical Support Email',
      documentation: 'Online Documentation',
      documentationDesc: 'View detailed usage documentation and API specifications'
    }
  },
};
