// English language pack.
export default {
  // Common parts
  common: {
    confirm: "Confirm",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    failed: "Failed",
    warning: "Warning",
    loading: "Loading",
    noData: "No Data",
    save: "Save",
    reset: "Reset",
    retry: "Retry",
    back: "Back",
    close: "Close",
    view: "View",
    index: "No.",
    operation: "Operation",
    running: "Running",
    finished: "Finished",
    Tip: "(Generated by AI)",
    aiDisclaimer: "Generated by AI. Please exercise discretion.",
    followSystem: "Follow system",
    lightTheme: "Light",
    darkTheme: "Dark",
    themeSelector: "Choose theme",
    languageSelector: "Choose language",
    languageChinese: "中文",
    languageEnglish: "English",
    languageChineseCompact: "中",
    languageEnglishCompact: "EN",
    opFailedRetry: "Operation failed, please try again",
    renamedSuccess: "Renamed successfully",
    renameFailedRetry: "Rename failed, please try again",
    deletedSuccess: "Deleted successfully",
    deleteFailedRetry: "Delete failed, please try again",
    refreshedSuccess: "Refreshed successfully",
    refreshFailed: "Refresh failed",
    refreshFailedRetry: "Refresh failed, please try again",
    userAddedSuccess: "User added successfully",
    userUpdatedSuccess: "User updated successfully",
    registrationSuccess: "Registration successful",
    sessionExpired: "Your session has expired, please log in again",
    notice: "Notice",
  },

  // Error pages
  errorPage: {
    back: "Back",
    goHome: "Back to Home",
    goChat: "Open Chat",
    e401Title: "401 Error!",
    e401NoAccess: "You do not have access permission!",
    e401Detail:
      "Sorry, you do not have access permission. Please do not perform illegal operations. You can return to the home page.",
    e404Title: "404 Error!",
    e404NotFound: "Page not found!",
    e404Detail:
      "Sorry, the page you are looking for does not exist. Try checking the URL for errors, then press the refresh button on your browser or try to find something else in our application.",
  },

  // App information
  app: {
    title: "Phytomni",
  },

  // Interactive Tutorial
  tutorial: {
    step1: {
      title: "Welcome to Phytomni!",
      content:
        'First, let\'s get to know the navigation. Quick access to functions: "Start New" initiates a brand-new task, "Deep Genome Database" allows you to view gene information, "Favorites" is for collecting frequently-used content, and there are also historical interactions categorized by time to help you efficiently find past records.',
    },
    step2: {
      title: "Explore agent cases",
      content:
        "Browse the cases below the composer to open an existing agent demonstration.",
    },
    step3: {
      title: "Conversation Window",
      content:
        'This is the "window" for communicating with Phytomni. You can directly enter questions, or choose different intelligent assistants such as "ChatAgent" and "KnowledgeAgent" by yourself. Try clicking the input box. Are you ready to start exploring?',
    },
    nextStep: "Next Step",
    prevStep: "Previous",
    complete: "Complete",
    startTutorial: "Start Tutorial",
    navigationHint:
      "💡 Tip: Use ← → arrow keys or spacebar to navigate, ESC to exit",
  },

  // Menu
  menu: {
    deepGenome: "Deep Genome Database",
    favorites: "Favorites",
    feedback: "Feedback",
    userList: "User List",
    logList: "System Monitor",
    permissionManage: "Permissions",
    taskManager: "Task Management",
    globalConfig: "Global Policy Config",
    adminManagement: "Admin Management",
  },

  // Error codes
  errorCode: {
    401: "Authentication failed, unable to access system resources",
    403: "Current operation is not authorized",
    404: "Requested resource does not exist",
    default: "Unknown system error, please report to administrator",
  },

  // Request layer (used by axios interceptor)
  request: {
    sessionExpired: "Your session has expired. Please log in again.",
    sessionInvalid: "Invalid or expired session. Please log in again.",
    confirmButtonText: "OK",
    networkError: "Backend connection failed",
    requestTimeout: "Request timed out",
    httpStatusError: "Server error ({code})",
  },

  // Change password
  changePassword: {
    usernamePlaceholder: "Please enter username",
    oldPassword: "Old Password",
    oldPasswordPlaceholder: "Please enter old password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Please enter new password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Please confirm new password",
    confirm: "Confirm Change",
    usernameRequired: "Please enter username",
    oldPasswordRequired: "Please enter old password",
    newPasswordRequired: "Please enter new password",
    confirmPasswordRequired: "Please confirm new password",
    passwordMinLength: "Password must be at least 6 characters",
    passwordMinLength8: "Password must be at least 8 characters",
    passwordNeedUppercase: "Password must contain uppercase letters",
    passwordNeedLowercase: "Password must contain lowercase letters",
    passwordNeedNumber: "Password must contain numbers",
    passwordNeedSpecial: "Password must contain special characters",
    passwordSame: "New password cannot be the same as old password",
    passwordMismatch: "Passwords do not match",
    formValidationFailed: "Please check the form for errors",
    passwordChangeSuccess: "Password changed successfully",
    passwordChangeFailed: "Failed to change password",
    passwordChangeRetry: "Failed to change password, please try again later",
  },

  // Login module
  login: {
    title: "Sign in",
    subtitle: "A multi-agent system for scientific discovery and plant design",
    email: "Email",
    emailPlaceholder: "Please enter your email address",
    password: "Password",
    passwordPlaceholder: "8-16 characters, case sensitive",
    forgotPassword: "Forgot password?",
    loginButton: "Login",
    noAccount: "No account?",
    register: "Register",
    login: "Login",
    loginSuccess: "Login successful",
    loginFailed: "Login failed",
    registerFailed: "Registration failed",
    passwordWarningTitle: "Password Security Notice",
    accountLockedTitle: "Account Locked",
    firstLoginTitle: "First Login Notice",
    firstLoginMessage:
      "This is your first login. For security purposes, please change your initial password.",
    firstLoginEnforceTitle: "Password Change Required",
    firstLoginEnforceMessage:
      "You must change your initial password before accessing other pages.",
    validation: {
      emailRequired: "Please enter your email",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter your password",
      passwordLength: "Password must be 8-16 characters long",
    },
    agreement: {
      prefix:
        "Registering and logging in means you have read and agreed to our",
      terms: "Terms of Service",
      and: "and",
      privacy: "Privacy Policy",
    },
  },

  // Register module
  register: {
    title: "Create Account",
    subtitle: "Create your Phytomni account",
    closedTitle: "Registration unavailable",
    closedSubtitle: "New account registration is currently closed.",
    closedDescription: "Please contact an administrator to open an account.",
    returnToLogin: "Return to Login",
    email: "Email",
    emailPlaceholder: "Please enter your email address",
    password: "Password",
    passwordPlaceholder: "Please enter your password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Please confirm your password",
    registerButton: "Register",
    registrationFailed: "Registration failed",
    haveAccount: "Already have an account?",
    login: "Login",
    agreement: {
      prefix: "By registering, you agree to our",
      terms: "Terms of Service",
      and: "and",
      privacy: "Privacy Policy",
      checkboxLabel: "I have read and agree to the legal documents below",
      checkboxRequired:
        "Please agree to the Terms of Service and Privacy Policy",
    },
    validation: {
      emailRequired: "Please enter your email address",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter your password",
      passwordMinLength8: "@:changePassword.passwordMinLength8",
      passwordMaxLength16: "Password must not exceed 16 characters",
      passwordNeedUppercase: "@:changePassword.passwordNeedUppercase",
      passwordNeedLowercase: "@:changePassword.passwordNeedLowercase",
      passwordNeedNumber: "@:changePassword.passwordNeedNumber",
      passwordNeedSpecial: "Password must contain special characters",
      confirmPasswordRequired: "Please confirm your password",
      confirmPasswordMismatch: "Passwords do not match",
      formValidationFailed: "Please check the form for errors",
    },
  },

  legal: {
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    icpFiling: "京ICP备07026971号-9",
    versionLabel: "Version",
    effectiveLabel: "Effective date",
    draftBanner:
      "Draft pending review by Biotechnology Research Institute, CAAS. Not a final legal instrument.",
    loadError: "Unable to load this document. Please try again later.",
  },

  // Forgot password module
  forgotPassword: {
    title: "Forgot Password",
    backToLogin: "Back to Login",
    unavailableTitle: "Password Reset Not Yet Available",
    unavailableMessage:
      "This feature is under development. Please contact your system administrator to reset your password.",
  },

  // User management
  user: {
    list: "User List",
    listTitle: "User List",
    passwordEditPlaceholder: "Leave blank to keep the password unchanged",
    unnamedUser: "Unnamed user",
    add: "Add User",
    edit: "Edit User",
    username: "Username",
    password: "Password",
    role: "Role",
    roleSelect: "Please select a role",
    admin: "Administrator",
    addFailed: "Add failed",
    editFailed: "Edit failed",
    detail: "User Details",
    changePassword: "Change Password",
    feedback: "Feedback",
    logout: "Logout",
    history: "History",
    profile: "Profile",
    cloudStorage: "Cloud Storage",
    systemMonitor: "System Monitor",
    globalConfig: "Global Policy Config",
    adminManagement: "Admin Management",
    unlock: "Unlock",
    unlockConfirmTitle: "Unlock User",
    unlockConfirmMessage: "Are you sure you want to unlock user {email}?",
    unlockSuccess: "User unlocked successfully",
    unlockFailed: "Failed to unlock user",
    phone: "Phone",
    phonePlaceholder: "Please enter phone number",
    organization: "Organization",
    organizationPlaceholder: "Please enter organization",
    position: "Position",
    positionPlaceholder: "Please enter position",
    lastLoginAt: "Last Login",
    notLoggedIn: "Not logged in",
    chatLimit: "Chat Limit",
    chatLimitPlaceholder: "Please enter chat limit",
    unlimited: "Unlimited",
    validation: {
      emailRequired: "Please enter username",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter password",
      passwordLength: "Length must be between 8 and 16 characters",
      passwordMinLength8: "@:changePassword.passwordMinLength8",
      passwordMaxLength16: "Password must not exceed 16 characters",
      passwordNeedUppercase: "@:changePassword.passwordNeedUppercase",
      passwordNeedLowercase: "@:changePassword.passwordNeedLowercase",
      passwordNeedNumber: "@:changePassword.passwordNeedNumber",
      passwordNeedSpecial: "Password must contain special characters",
      roleRequired: "Please select a role",
      formValidationFailed: "Please check the form for errors",
    },
  },

  // Gene display
  gene: {
    detailTitle: "Gene research result",
    notFound: "Gene details not found",
    searchPlaceholder: "Please enter species or gene to search",
    getFailed: "Failed to get gene details",
    geneName: "File Name",
    biocode: "species",
    geneId: "Gene ID",
    resultsCount: "{count} results",
    logs: {
      fetchDataFailed: "Failed to fetch data:",
      fetchDetailFailed: "Failed to fetch gene details:",
    },
  },

  // Chat module
  chat: {
    untitledConversation: "New chat",
    conversationTitle: "Conversation title",
    appTitle: "Phytomni",
    welcome: "Welcome, please enter your question directly",
    inputPlaceholder: "Please enter your question...",
    send: "Send",
    newChat: "Start New",
    openNavigation: "Open navigation",
    expandNavigation: "Expand navigation",
    collapseNavigation: "Collapse navigation",
    exploreAgent: "Explore Agents",
    agentsArchitectureTitle: "Phytomni Agent Architecture",
    agentsArchitectureAlt: "Phytomni agent architecture diagram",
    deepGenome: "Deep Genome Database",
    useTool: "Use Tool",
    stepResult: "Step Result",
    resultImageAlt: "Result image {index}",
    sendFailed: "Failed to send message, please try again later.",
    timeoutFailed:
      "The request timed out. Try narrowing your query or retry later.",
    contextDegraded:
      "Answer saved. Conversation context will be rebuilt on the next message.",
    routingFallbackChat:
      "No specialized agent was identified; this turn fell back to Chat.",
    routingSelectedAgent: "{agent}",
    requestId: "Request ID",
    sendAriaLabel: "Send",
    abortAriaLabel: "Stop answering",
    progress: {
      processing: "Processing",
      selectingAgent: "Selecting an agent…",
      valueText: "Processing, {percent}%",
      etaSeconds: "Usually {min}–{max} seconds",
      etaMinutes: "Usually {min}–{max} min",
      etaHours: "Usually {min}–{max} hours",
      cotLabel: "Working steps",
      cotCount: "{shown}/{total}",
      stages: {
        chat: {
          prepareContext: "Preparing conversation context",
          generate: "Writing the answer",
          followUp: "Preparing follow-up questions",
        },
        knowledge: {
          processFiles: "Processing attached files",
          retrieve: "Searching the literature",
          prepareGenerate: "Preparing the cited draft",
          generate: "Writing the cited answer",
          assemble: "Assembling citations",
          prepareFollowUp: "Preparing follow-up prompts",
          followUp: "Writing follow-up questions",
        },
        data: {
          prepareRetrieve: "Preparing catalog lookup",
          searchKnowledge: "Checking related knowledge",
          collectRetrieve: "Collecting catalog matches",
          prepareRewrite: "Preparing query rewrite",
          rewriteQuery: "Rewriting the data query",
          applyRewrite: "Applying the rewritten query",
          searchCatalog: "Searching the data catalog",
        },
        briefGene: {
          parseQuery: "Reading the gene query",
          fetchAnnotation: "Fetching gene annotations",
          prepareRetrieve: "Preparing literature tasks",
          retrieveWorker: "Searching related literature",
          retrieveReduce: "Merging literature hits",
          prepareGenerate: "Preparing the gene brief",
          generate: "Writing the gene brief",
          prepareFollowUp: "Preparing follow-up prompts",
          followUp: "Writing follow-up questions",
        },
        review: {
          planPrep: "Preparing review questions",
          planPost: "Locking the review plan",
          retrieveDispatch: "Dispatching literature retrieval",
          retrieveWorker: "Retrieving literature",
          retrieveReduce: "Merging retrieved evidence",
          draftDispatch: "Dispatching section drafts",
          draftWorker: "Drafting review sections",
          draftReduce: "Merging drafted sections",
          reviewDispatch: "Dispatching section review",
          reviewWorker: "Reviewing drafted sections",
          reviewReduce: "Merging review notes",
          reviseDispatch: "Dispatching revisions",
          reviseWorker: "Revising the manuscript",
          reviseReduce: "Merging revised sections",
          summaryPrep: "Preparing the review summary",
          summaryPost: "Writing the review summary",
          prepareFollowUp: "Preparing follow-up prompts",
          followUp: "Writing follow-up questions",
        },
        analyst: {
          parsePrep: "Preparing to parse the request",
          parsePost: "Parsing the analysis request",
          selectPrep: "Preparing data selection",
          selectPost: "Selecting datasets",
          methodPrep: "Preparing method lookup",
          methodKnowledge: "Retrieving analysis methods",
          methodPost: "Locking selected methods",
          planPrep: "Preparing the analysis plan",
          planPost: "Writing the analysis plan",
          checkPrep: "Preparing plan checks",
          checkPost: "Checking the analysis plan",
          toolExtractPrep: "Preparing tool extraction",
          toolExtractPost: "Extracting required tools",
          toolRetrieve: "Retrieving tool configurations",
          submit: "Submitting compute jobs",
          pool: "Waiting for analysis results",
        },
        deepGenome: {
          brief: "Writing the gene background",
          prepare: "Preparing multi-omics tasks",
          tissues: "Collecting tissue expression",
          cultivars: "Collecting cultivar expression",
          treatments: "Collecting treatment expression",
          genotypes: "Collecting genotype expression",
          singleCell: "Collecting single-cell evidence",
          promoter: "Collecting promoter evidence",
          smep: "Collecting SMEP evidence",
          smoc: "Collecting SMOC evidence",
          protein: "Collecting protein structure",
          design: "Collecting design evidence",
          evolution: "Collecting evolution evidence",
          synthesize: "Synthesizing collected evidence",
          experiment: "Drafting suggested experiments",
          protocol: "Drafting protocols",
          discussion: "Writing the discussion",
          summary: "Writing the deep-genome summary",
          followUp: "Preparing follow-up questions",
        },
        design: {
          prepare: "Preparing protein and promoter design tasks",
          protein: "Submitting protein design",
          promoter: "Submitting promoter design",
          resume: "Resuming external design work",
          wait: "Waiting for design results",
        },
        network: {
          prepare: "Preparing network analysis",
          submit: "Submitting network analysis",
          build: "Building the regulatory network",
          wait: "Waiting for network results",
        },
        research: {
          validate: "Validating the research request",
          resolveInputs: "Resolving research inputs",
          extract: "Extracting research goals",
          plan: "Planning in-silico experiments",
          prepare: "Preparing research tasks",
          run: "Running analysis tasks",
          resume: "Resuming external research work",
          pack: "Waiting for results and packaging",
        },
      },
    },
    botReport: {
      waiting: "Preparing the report",
      partial: "Partial report available",
      degraded: "Some analysis is unavailable",
      failed: "Report generation failed",
      inputRequired: "More information is required",
      complete: "Report ready",
      emptyArtifacts: "No downloadable artifacts are available.",
    },
    generationStopped: "Generation stopped",
    relatedDocuments: "Reference Material",
    welcomeTitle: "What would you like to explore?",
    history: {
      loading: "Loading conversation history",
      emptyTitle: "This conversation has no messages yet",
      emptySubtitle: "Start with a question to continue this conversation.",
      errorTitle: "Conversation history could not be loaded",
      errorSubtitle:
        "Please try again. Your other conversations are unchanged.",
      retry: "Try again",
    },
    mode: {
      instant: "Instant",
      expert: "Expert",
      comingSoon: "Coming soon",
    },
    tools: {
      generic: "Calling a tool",
      knowledge_search: "Searching literature",
    },
    steps: {
      retrieving: "Retrieving",
    },
    toolHits: "{count} hits",
    streamInterrupted: "Connection interrupted, please retry.",
    activity: {
      label: "Activity",
      count: "{count}",
      status: {
        running: "In progress",
        done: "Done",
      },
    },
    a2ui: {
      confirm: "Confirm",
      cancel: "Cancel",
      submit: "Submit",
      submitting: "Waiting for the action to finish.",
      submitted: "This action was submitted.",
      cancelled: "This action was cancelled.",
      rejected: "This action was rejected.",
      advanced: "This action was superseded.",
      temporarilyRejected: "This action can be retried.",
      retry: "Retry action",
      expired: "This prompt is no longer active.",
      unknown: "This action has an unknown result.",
      protocolError: "This action could not be displayed.",
      notSent: "This action was not sent.",
      refreshRequired: "Refresh the conversation to continue.",
      failed: "This prompt failed. Please retry the question.",
      locked: "Submitted",
    },
    reasoning: { show: "Show reasoning", hide: "Hide reasoning" },
    welcomeSubtitle:
      "Start with literature, a gene or species, or a deeper genomic analysis.",
    cases: {
      title: "Explore Agent Cases",
      ariaLabel: "Agent case demonstrations",
      askThisAgent: "Ask this agent",
      demoEmpty: {
        title: "No example conversation yet",
        body: "This is a static example. A sample report will be added later. You can ask this agent now.",
      },
      demoLoadError: {
        title: "Could not load this example",
        body: "Return to chat and try again, or ask this agent now.",
      },
    },
    inputPlaceholderTip: "Please enter your question",
    uploadFile:
      "Attach biological data or text files (up to 10 GiB each, {maxFiles} files). You can also paste copied files.",
    attachmentTargetUnavailable:
      "This agent can't accept attachments. Remove them or choose a compatible agent.",
    attachmentTargetUnsupported: "This agent does not accept file uploads.",
    attachmentErrors: {
      unsupported_type:
        '"{file}" is not supported by this Agent. Check the Agent capability before retrying.',
      file_too_large: '"{file}" exceeds the {maxFileMb} MB per-file limit.',
      total_too_large: "Attachments cannot exceed {maxTotalMb} MB in total.",
      too_many_files: "You can attach up to {maxFiles} files.",
      invalid_filename: '"{file}" has an invalid filename.',
      invalid_size: '"{file}" must be between 1 byte and 10 GiB.',
      invalid_metadata: '"{file}" has invalid file metadata.',
      upload_disabled: "File uploads are currently unavailable.",
      upload_unavailable: "The file upload service is temporarily unavailable.",
    },
    upload: {
      alreadyAttached: "Already attached: {file}",
      attachments: "Attachments",
      chipLabel: "{file}, {suffix}, {status}, {metric}",
      fileSuffixFallback: "FILE",
      more: "+{count} more",
      hiddenFailed: "{count} failed",
      hiddenExpired: "{count} expired",
      status: {
        queued: "Queued",
        creating: "Preparing",
        uploading: "Uploading",
        paused: "Paused",
        failed: "Upload failed",
        completing: "Finalizing",
        completed: "Ready to send",
        aborted: "Cancelled",
        expired: "Session expired",
      },
      stateChanged: "{file}: {status}",
      progress: "{loaded} / {total} ({percent}%)",
      progressLabel: "Upload progress for {file}",
      speed: "{rate}",
      eta: "About {seconds}s left",
      pause: "Pause",
      resume: "Resume",
      retry: "Retry",
      reselect: "Choose file",
      cancel: "Cancel",
      remove: "Remove",
      actions: {
        pause: "Pause upload for {file}",
        resume: "Resume upload for {file}",
        retry: "Retry upload for {file}",
        reselect: "Choose the original file for {file}",
        cancel: "Cancel upload for {file}",
        remove: "Remove {file}",
      },
      completedFile: "Completed file",
    },
    timeGroup: {
      today: "Today",
      yesterday: "Yesterday",
      week: "Within 7 Days",
      older: "Older Than a Week",
    },
    agentLabels: {
      chatAgent: "Chat Agent",
      knowledgeAgent: "Knowledge Agent",
      dataAgent: "Data Agent",
      analystAgent: "Analyst Agent",
      reviewAgent: "Review Agent",
      briefGeneAgent: "Brief Gene Agent",
      deepGenomeAgent: "Deep Genome Agent",
      inSilicoResearchAgent: "In Silico Research Agent",
      geneNetworkAgent: "Gene Network Agent",
      digitalDesignAgent: "Digital Design Agent",
    },
    agentPresentation: {
      chatAgentAlt: "Chat Agent workflow flowchart",
      knowledgeAgentAlt: "Knowledge Agent workflow flowchart",
      dataAgentAlt: "Data Agent workflow flowchart",
      analystAgentAlt: "Analyst Agent workflow flowchart",
      reviewAgentAlt: "Review Agent workflow flowchart",
      inSilicoResearchAgentAlt: "In Silico Research Agent workflow flowchart",
      geneNetworkAgentAlt: "Gene Network Agent workflow flowchart",
      deepGenomeAgentAlt: "Deep Genome Agent workflow flowchart",
      digitalDesignAgentAlt: "Digital Design Agent workflow flowchart",
    },
    agents: {
      chatAgent:
        "Your AI assistant for answering plant research questions in natural language.",
      knowledgeAgent: "Expert-curated plant knowledge at your fingertips.",
      dataAgent: "Handles and optimizes plant datasets for research.",
      analystAgent: "Transforms raw data into meaningful plant insights.",
      reviewAgent:
        "Generates AI-powered literature reviews for agricultural research.",
      briefGeneAgent: "Creates rapid gene-function briefs and research leads.",
      deepGenomeAgent: "Decodes plant genomes for smarter breeding strategies.",
      inSilicoResearchAgent:
        "Simulates plant experiments digitally to accelerate discovery.",
      geneNetworkAgent:
        "Decodes gene regulatory networks to uncover key pathways for crop stress resistance and yield.",
      digitalDesignAgent:
        "AI-driven design of gene promoters and protein structures for synthetic biology and molecular breeding.",
    },
    logs: {
      sendMessageFailed: "Failed to send message:",
    },
    downloadURL: "Download link",
    copySuccess: "Copied successfully",
    copyFailed: "Copy failed",
    pendingWriteFailed: "Session backup failed, sending unaffected",
    icpAriaLabel: "MIIT ICP filing",
    copy: "Copy",
    ladingInner:
      "Processing your request: retrieving data, analyzing information, and generating a response. Please wait",
    footer: "Generated by AI. Please carefully examine.",
    followUpQuestions: "Question Suggestions:",
    more: "More",
    actions: {
      rename: "Rename",
      favorite: "Favorite",
      unfavorite: "Unfavorite",
      delete: "Delete",
      deleteConfirm: "Confirm Delete",
      deleteWarning:
        "Are you sure you want to delete this conversation? This action cannot be undone.",
      enterNewTitle: "Please enter a new title",
      like: "Like",
      undoLike: "Undo like",
      dislike: "Dislike",
      undoDislike: "Undo dislike",
      downloadAttachments: "Download attachments",
      downloadFormats: "Download as format",
      download: "Download",
      attachments: "Attachments",
    },
    favorites: "Favorites",
    noFavorites: "No Favorites",
    noFavoritesDescription:
      "You haven't favorited any conversations yet. Start chatting and favorite the content you like",
    startChat: "Start Chat",
    favoritesCount: "{count} Favorites",
    openChat: "Open Chat",
    refresh: "Refresh",
    loveThis: "Love this",
    needsImprovement: "Needs Improvement",
    hideLog: "Hide Log",
    showLog: "View Log",
    downloadFile: "Download File",
    testParallel: "Test parallel chats",
    refreshReply: "Refresh reply",
    refreshConversationGone:
      "This conversation is no longer available. Open it again from the sidebar.",
    abortTooltip: "Abort answer",
    loadingAgentPerms: "Loading agent permissions...",
    agentPicker: {
      loading: "Loading agent permissions...",
      empty: "No agents available for your account",
      noAvailableAgents: "No agents are available for this account.",
      auto: "Auto",
      label: "Choose an agent",
      searchPlaceholder: "Search agents…",
      noResults: "No matching agents",
      remove: "Remove {agent}",
    },
    log: {
      replyContent: "Reply Content",
      execLog: "Execution Log (ID: {id})",
      activityLabel: "Execution log",
      updateLog: "Update Log",
      updateUnavailable: "Update unavailable",
      loading: "Loading logs...",
      contentColumn: "Log Content",
      noData: "No log data",
      unavailable: "Log unavailable",
      fetchError: "Failed to load log",
      updateError: "Failed to update log",
      retry: "Retry",
      reconnecting: "Reconnecting to the Agent log…",
      pending: "The Agent log is not available yet.",
      terminalEmpty: "This Agent run completed without a log.",
      truncated: "Only the available portion of this log is shown.",
      historicalRefresh: "Refresh historical log",
    },
    lifecycle: {
      preparing: "Preparing",
      resolving_inputs: "Resolving inputs",
      planning: "Planning tasks",
      running: "Running",
      finalizing: "Finalizing",
      succeeded: "Succeeded",
      failed: "Failed",
      timed_out: "Timed out",
      cancelled: "Cancelled",
      resultUnavailable:
        "The task finished, but the report is not yet available.",
      childKindFallback: "Child {ordinal}",
      childKind: {
        analyst: "Analysis",
        research: "Research unit",
        network: "Network analysis",
        design: "Design analysis",
        protein_structure_analysis: "Protein structure",
        promoter_analysis: "Promoter design",
        protein_design_analysis: "Protein design",
        promoter_design_analysis: "Promoter design",
        gene_network_analysis: "Gene network analysis",
      },
      childError: {
        input_rejected:
          "This child was rejected because the input is not valid.",
        plan_rejected: "This child was rejected because the plan is not valid.",
        remote_failed: "This child did not succeed.",
        remote_cancelled: "This child was cancelled.",
        fallback: "This child did not succeed.",
      },
    },
    logUpdatedSuccess: "Log updated successfully",
    logUpdateFailed: "Failed to update log",
    logUpdateFailedRetry: "Failed to update log, please try again",
    liked: "Liked",
    disliked: "Disliked",
    cancelled: "Cancelled",
    printFailed: "Print failed",
    transferCancel: "Cancel",
    transferEta: "About {seconds}s left",
    transferSize: "{loaded} / {total}",
    transferProgress: "Active transfers",
    transferPhase: {
      upload: "Uploading",
      download: "Downloading",
    },
    transferProgressText: "{phase}: {loaded} / {total} ({percent}%)",
    transferProgressIndeterminate: "{phase}: {loaded} transferred",
    downloadCancelled: "Download cancelled",
    downloadError:
      "An error occurred while downloading, please contact the administrator!",
    resultArchive: {
      preparing: "Preparing result archive",
      download: "Download {name}",
      generationFailed: "Result archive generation failed",
      none: "Completed with no downloadable attachments",
      manifestInvalid: "Completed, but attachment packaging is incomplete",
      unavailable: "Result archive is not available",
      retry: "Retry archive generation",
      retrying: "Retrying archive generation",
      retryFailed: "The archive retry could not be started.",
      downloadFailed: "The result archive could not be downloaded.",
    },
  },

  // History module
  history: {
    noHistory: "No history yet",
    noHistoryDescription:
      "You don't have any chat history yet. Start chatting and view your conversation history",
    historyCount: "{count} history records",
    loadFailed: "Failed to load history",
  },

  // Favorites module
  favorites: {
    loadFailed: "Failed to load favorites",
    removedSuccess: "Removed from favorites",
    removeFailed: "Failed to remove favorite",
    addedSuccess: "Added to favorites",
  },

  // Profile management module
  profile: {
    title: "Profile Management",
    description:
      "Manage your personal information, account security and usage statistics",
    basicInfo: {
      title: "Basic Information",
      username: "Username",
      email: "Email",
      phone: "Phone",
      organization: "Organization",
      position: "Position",
    },
    security: {
      title: "Account Security",
      password: "Login Password",
      passwordDescription:
        "Change your password regularly to ensure account security",
      changePassword: "Change Password",
      permission: "User Permission",
      permissionDescription: "Current account permission level",
      oldPassword: "Old Password",
      oldPasswordPlaceholder: "@:changePassword.oldPasswordPlaceholder",
      newPassword: "New Password",
      newPasswordPlaceholder: "@:changePassword.newPasswordPlaceholder",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "@:changePassword.confirmPasswordPlaceholder",
    },
    usage: {
      title: "Usage Statistics",
      totalChats: "Total Chats",
      lastLogin: "Last Login",
    },
    passwordChangeSuccess: "Password changed successfully",
    passwordChangeFailed: "Failed to change password, please try again",
    userInfoNotFound: "User information not found",
    fetchUserInfoFailed: "Failed to fetch user information",
    fetchUserInfoError: "Failed to fetch user information",
  },

  // Cloud storage module
  cloudStorage: {
    title: "Cloud Drive (Beta)",
    description:
      "This is a simplified preview. Some features are still under construction.",
    tryDemo: "Try Demo",
  },

  // Log management
  log: {
    list: "Log List",
  },

  // Permission management
  permission: {
    title: "Permissions",
  },

  // Task management
  taskManager: {
    question: "Question",
    status: "Status",
    updated_at: "Updated Time",
    downloadURL: "Download",
    dialogue_link: "Link",
    getFailed: "Failed to get list",
    logs: {
      fetchDataFailed: "Failed to obtain data list",
    },
    operate: "Operate",
    cancel: "Cancel",
    cancelFailed: "Task cancellation is no longer available",
  },

  // User Feedback
  feedback: {
    placeholder:
      "Please describe your questions, suggestions, or feedback in detail...",
    submit: "Submit Feedback",
    submitSuccess:
      "Feedback submitted successfully. Thank you for your valuable input!",
    submitFailed: "Submission failed, please try again",
    validation: {
      required: "Please enter feedback content",
      min: "Feedback must be at least 10 characters",
      max: "Feedback cannot exceed 1000 characters",
    },
  },

  // Global Policy Configuration
  globalConfig: {
    description: "Manage system global policies and security configurations",
    systemSettings: "System Settings",
    basicSettings: "Basic Configuration",
    securitySettings: "Security Policy",
    featureSettings: "Feature Configuration",
    systemName: "System Name",
    systemNamePlaceholder: "Please enter system name",
    maxFileSize: "Max File Size",
    sessionTimeout: "Session Timeout",
    minutes: "minutes",
    passwordPolicy: "Password Policy",
    requireUppercase: "Require Uppercase",
    requireLowercase: "Require Lowercase",
    requireNumbers: "Require Numbers",
    requireSymbols: "Require Symbols",
    loginAttempts: "Max Login Attempts",
    attempts: "attempts",
    ipWhitelist: "IP Whitelist",
    ipWhitelistPlaceholder: "Please enter IP addresses, one per line",
    enableFileUpload: "Enable File Upload",
    enableChatHistory: "Enable Chat History",
    maxChatHistory: "Max Chat History Records",
    records: "records",
    testConfig: "Test Configuration",
    configHistory: "Configuration History",
    timestamp: "Timestamp",
    operator: "Operator",
    changes: "Changes",
    historyDetail: "History Detail",
    historyDetailContent:
      "Time: {time}\nOperator: {operator}\nChanges: {changes}",
    saveSuccess: "Configuration saved successfully",
    saveFailed: "Failed to save configuration",
    resetConfirm:
      "Are you sure you want to reset all configurations to default values?",
    resetSuccess: "Configuration reset successfully",
    testUnavailable: "Configuration test is not yet wired to the backend",
  },

  // Agent Pages
  agents: {
    demo: {
      staticExample: "Static example",
      questionLabel: "Example question",
    },
    analyst: {
      title: "Analyst Agent",
      subtitle:
        "Submit an analysis objective and datasets for a structured bioinformatics report.",
      agentLabel: "Analysis workflow",
      questionLabel: "Analysis question",
      questionPlaceholder:
        "Describe the analysis, species, and comparison you need",
      contextFilesLabel: "Analysis files",
      contextFilesHint:
        "Attach supported documents or biological data, up to {maxFiles} files and {maxFileSize} each.",
      submit: "Start analysis run",
      submitting: "Submitting…",
      reset: "Start another run",
      progress: "Analysis run in progress",
      complete: "Report ready",
      degraded: "The report is partial because some analysis was unavailable.",
      unsupportedAssetFormat:
        "This Agent cannot process that asset format. The upload completed; choose an input format supported by this Agent.",
      reportTitle: "Analysis report",
      report: "Report",
      evidence: "Evidence",
      activity: "Activity",
      downloads: "Downloads",
      download: "Request download",
      noEvidence: "No structured evidence is available for this run.",
      noDownloads: "No safe downloads are available for this run.",
      emptyReport: "The analysis report is not available yet.",
      capabilityLoading: "Checking analysis capability…",
      unavailableTitle: "Analyst Agent is not available",
      unavailableMessage:
        "This route is reserved for a capability-gated analysis workflow. No result was created.",
      questionRequired: "Enter an analysis question before submitting.",
      questionTooLong: "The analysis question is too long.",
      submitFailed:
        "The analysis run could not be submitted. Please try again.",
      downloadFailed: "The download request could not be completed.",
      sectionsLabel: "Analysis report sections",
    },
    data: {
      title: "Data Agent",
      subtitle:
        "Data Agent - Provides multi-omics data analysis and processing services",
      tableCaptions: {
        transcript: "Sample output — transcript ID",
        cdsLength: "Sample output — CDS length",
        homologs: "Sample output — homologous genes",
      },
    },
    review: {
      title: "Review Agent",
      subtitle:
        "Review Agent - Provides structured literature reviews for plant research topics",
    },
    briefGene: {
      title: "Brief Gene Agent",
      subtitle:
        "Brief Gene Agent - Provides rapid gene-function briefs and research leads",
    },
    knowledge: {
      title: "Knowledge Agent",
      subtitle:
        "Knowledge Agent - Provides bioinformatics knowledge query and analysis services",
    },
    deepGenome: {
      title: "Deep Genome Agent",
      subtitle:
        "Deep Genome Agent - Provides in-depth analysis services for species and genes",
      taskCreated: "Task created successfully",
      downloadPDF: "Download PDF",
      downloadMD: "Download Markdown",
      imageViewerTitle: "Image Viewer",
      references: "References",
      noReferences: "No references available.",
    },
    geneNetwork: {
      title: "Gene Network Agent",
      subtitle:
        "Gene Network Agent - Provides gene network analysis and phenotype trait association services",
      sampleTask: "Static sample task ID",
      sampleResult: "Static sample result",
      downloadResults: "Start download requests",
      startingDownload: "Starting download {current} of {total}",
      allDownloadsStarted: "All five download requests started",
      agentLabel: "Gene network workflow",
      questionLabel: "Network question",
      questionPlaceholder:
        "Describe the trait network analysis you want to explore",
      traitLabel: "Trait Ontology target",
      traitPlaceholder: "Choose a supported trait",
      speciesLabel: "Species",
      speciesPlaceholder: "Choose a supported species",
      submit: "Start network run",
      submitting: "Submitting…",
      reset: "Start another run",
      progress: "Gene network run in progress",
      complete: "Gene network report ready",
      degraded:
        "The gene network report is partial because some analysis was unavailable.",
      trackingDegraded:
        "Run tracking is degraded. The displayed state may not include the latest Bot update.",
      reportTitle: "Gene network report",
      report: "Report",
      evidence: "Evidence",
      activity: "Activity",
      downloads: "Downloads",
      download: "Request download",
      noEvidence: "No structured evidence is available for this run.",
      noDownloads: "No safe downloads are available for this run.",
      emptyReport: "The gene network report is not available yet.",
      capabilityLoading: "Checking gene network capability…",
      unavailableTitle: "Gene Network Agent is not available",
      unavailableMessage:
        "This route is reserved for a capability-gated gene network workflow. No result was created.",
      questionRequired: "Enter a network question before submitting.",
      questionTooLong: "The network question is too long.",
      traitValidation: "Choose a supported Trait Ontology target.",
      speciesValidation: "Choose a supported species.",
      submitFailed:
        "The gene network run could not be submitted. Please try again.",
      downloadFailed: "The download request could not be completed.",
      sectionsLabel: "Gene network report sections",
      traits: {
        nitrogenSensitivity: "Nitrogen sensitivity",
        seedlingHeight: "Seedling height",
        panicleLength: "Panicle length",
        harvestIndex: "Harvest index",
        plantHeight: "Plant height",
        germinationRate: "Germination rate",
      },
      species: {
        arabidopsis: "Arabidopsis thaliana",
        rice: "Rice",
        maize: "Maize",
        sorghum: "Sorghum",
        soybean: "Soybean",
      },
    },
    digitalDesign: {
      title: "Digital Design Agent",
      subtitle:
        "Digital Design Agent - Provides protein structure prediction and design services based on gene IDs",
      sampleTask: "Static sample task ID",
      sampleResult: "Static sample result",
      downloadResults: "Start download request",
      agentLabel: "Digital design workflow",
      questionLabel: "Design question",
      questionPlaceholder:
        "Describe the protein or promoter design you want to explore",
      geneIdLabel: "Gene ID",
      geneIdPlaceholder: "For example, AT1G01010",
      speciesCodeLabel: "Species code",
      speciesCodePlaceholder: "For example, ath",
      contextFilesLabel: "Context files (optional)",
      contextFilesHint:
        "Attach biological or text data in any format, up to 10 files and 10 GiB each.",
      submit: "Start design run",
      submitting: "Submitting…",
      reset: "Start another run",
      progress: "Design run in progress",
      complete: "Design report ready",
      degraded:
        "The design report is partial because some analysis was unavailable.",
      unsupportedAssetFormat:
        "This Agent cannot process that asset format. The upload completed; choose an input format supported by this Agent.",
      trackingDegraded:
        "Run tracking is degraded. The displayed state may not include the latest Bot update.",
      reportTitle: "Digital design report",
      report: "Report",
      evidence: "Evidence",
      activity: "Activity",
      downloads: "Downloads",
      download: "Request download",
      noEvidence: "No structured evidence is available for this run.",
      noDownloads: "No safe downloads are available for this run.",
      emptyReport: "The design report is not available yet.",
      capabilityLoading: "Checking digital design capability…",
      unavailableTitle: "Digital Design Agent is not available",
      unavailableMessage:
        "This route is reserved for a capability-gated design workflow. No result was created.",
      fileValidation:
        "Some files were rejected. Check the file metadata and 10 GiB size limit.",
      fileCountValidation: "You can upload at most 10 files.",
      questionRequired: "Enter a design question before submitting.",
      questionTooLong: "The design question is too long.",
      geneIdValidation:
        "Enter a valid gene ID using letters, numbers, dots, underscores, or hyphens (up to 128 characters).",
      speciesCodeValidation:
        "Enter a valid species code using lowercase letters, numbers, underscores, or hyphens (up to 32 characters).",
      submitFailed: "The design run could not be submitted. Please try again.",
      downloadFailed: "The download request could not be completed.",
      sectionsLabel: "Digital design report sections",
    },
    design: {
      title: "Design Agent",
      subtitle:
        "Design Agent - Legacy compatibility route for the capability-gated Digital Design workflow",
      unavailableTitle: "Design Agent is not yet available",
      unavailableMessage:
        "This legacy route remains unavailable. Use the Digital Design Agent route when its capability is enabled.",
    },
    research: {
      title: "In Silico Research Agent",
      agentLabel: "Research workflow",
      subtitle:
        "Submit a study question and supporting context for a reproducible research report.",
      questionLabel: "Research question",
      questionPlaceholder:
        "Describe the study you want to reproduce or explore",
      contextFilesLabel: "Paper and context files",
      contextFilesHint:
        "Attach papers or biological data in any format, up to {maxFiles} files and {maxFileSize} each.",
      submit: "Start research run",
      submitting: "Submitting…",
      reset: "Start another run",
      progress: "Research run in progress",
      complete: "Report ready",
      degraded: "The report is partial because some analysis was unavailable.",
      unsupportedAssetFormat:
        "This Agent cannot process that asset format. The upload completed; choose an input format supported by this Agent.",
      reportTitle: "Research report",
      report: "Report",
      evidence: "Evidence",
      activity: "Activity",
      downloads: "Downloads",
      download: "Request download",
      noEvidence: "No structured evidence is available for this run.",
      noDownloads: "No safe downloads are available for this run.",
      emptyReport: "The research report is not available yet.",
      capabilityLoading: "Checking research capability…",
      unavailableTitle: "Research Agent is not available",
      unavailableMessage:
        "This route is reserved for a capability-gated research workflow. No result was created.",
      fileValidation:
        "Some files were rejected. Check the file metadata and 10 GiB size limit.",
      fileCountValidation: "You can upload at most 10 files.",
      questionRequired: "Enter a research question before submitting.",
      questionTooLong: "The research question is too long.",
      submitFailed:
        "The research run could not be submitted. Please try again.",
      downloadFailed: "The download request could not be completed.",
      sectionsLabel: "Research report sections",
    },
  },

  // Help Center
  help: {
    title: "Help Center",
    tableOfContents: "Table of Contents",
    goBackTokenExpired: "Login expired, please log in again",
    goBackFailed: "Failed to go back to previous page",
    toc: {
      whatIs: "What is Phytomni?",
      gettingStarted: "Getting Started",
      howItWorks: "How does Phytomni work?",
      resources: "What resources does Phytomni integrate?",
      limitations: "Limitations and Best Practices",
    },
    doc: {
      whatIs: {
        heading: "1. What is Phytomni?",
        body: `Phytomni is an intelligent agentic AI system for scientific discovery and design in plant research, which can assist researchers to significantly accelerate scientific discovery, including:

-   Answering diverse scientific questions directly with natural language queries;
-   Unlocking insights from over 4 million full-text scientific articles, extracting reliable insights, and providing direct answers with source references;
-   Integrating and analyzing 14 types of omics datasets covering 65 plant species to generate precise digital insights;
-   Accepting user-submitted data and task requirements, and autonomously planning and executing bioinformatics analyses;

Building upon these core capabilities, Phytomni can perform complex research tasks, including but not limited to:

-   Automated integration of literature and generation of domain review reports;
-   Integrating multi-dimensional information to analyze gene function and write professional reports;
-   Automating key steps in the reproduction of published scientific studies;
-   Discovering new biological pathways (such as hormone-gene-phenotype network analysis);
-   Designing and optimizing alleles and proteins (including gene promoters and protein engineering);
-   **... ...**`,
      },
      gettingStarted: {
        heading: "2. Getting Started: How to Use Phytomni",
        body: `Using Phytomni is a conversational, task-oriented process. Follow these simple steps to begin your research:

### Step 1: Formulate and Submit Your Query

To start using Phytomni, the first step is to clearly formulate your research query. You need to select the corresponding **AGENT** button and describe your specific objectives as precisely as possible—whether they involve literature retrieval, data extraction, or analytical tasks. Clear and detailed instructions will ensure that Phytomni accurately captures your research needs and delivers high-quality results.

### Step 2: Monitor and Manage Your Task

After submitting your query, you can monitor its progress in real time through the **Task Management** module. This module provides an overview of your submitted tasks, including the original problem, task status, and the most recent update time.

### Step 3: Review and Explore Results

Once the task is completed, you will be able to review the results directly in the system. For example, when exploring specific genes, the Deep Genome Database module offers a comprehensive, integrated view of the target gene, including basic information, literature summaries, interaction networks, and expression heatmaps. You can download your results for further use or export them into different formats. To facilitate long-term research, completed tasks can also be saved as favourites, allowing you to easily revisit and reuse them whenever needed.`,
      },
      howItWorks: {
        heading:
          "3. How does Phytomni work? Understanding the Architecture and Capabilities",
        body: `### The Dual-LLM Core

The **Phytomni-Hub** module serves as the central intelligence for the entire system. This module integrates two domain-specific LLMs—**Phyto-Chatbot** and **Phyto-Reasoner**—both of which were pre-trained on knowledge from Phytomni's resource modules and fine-tuned with high-quality data. **Phyto-Chatbot** is capable of intent recognition and initiating data searches, while **Phyto-Reasoner** is responsible for reasoning, planning, and knowledge synthesis. The two work synergistically to support automated bioinformatic operations.

### A Team of AI Agents and Their Applications

Phytomni accomplishes tasks by orchestrating a team of specialized agents. Here's what each agent does and how you can use them:

-   The **Chat Agent** is your primary conversational interface with Phytomni. It answers various research questions in natural language, explains complex biological concepts, and provides guidance on experimental design or data analysis. This agent enables researchers to quickly gain actionable insights without having to manually navigate multiple databases.

-   The **Knowledge Agent** is built on a century-spanning agricultural knowledge base, integrating over 4 million full-text articles, 27 million abstracts, and nearly 200,000 structured patents. It supports natural language queries to retrieve and extract full-text information, generating evidence-based answers with complete source references—turning fragmented plant research into an accessible, authoritative discovery foundation.

-   The **Data Agent** is powered by a multi-omics database covering 65 plant species and 14 omics data types. It unifies 21 identifier types, corrects errors, removes redundancies, and standardizes entries. It intelligently translates your natural language query into a precise database query (SQL) to extract, cross-link, and visualize gene-centric or system-level biological data, enabling seamless exploration of plant genomes, expression profiles, and protein interactions.

-   The **Analyst Agent** functions like an automated bioinformatician, integrating a library of over 120 curated bioinformatics tools. It plans and executes complex tasks (such as sequence analysis or gene expression profiling) and embeds expert-validated pipelines into a user-friendly interface, enabling end-to-end multi-omics analyses without manual software installation or configuration.

-   The **Review Agent** automatically generates comprehensive literature reviews on targeted research topics. It interprets user queries to build a review plan, uses the Knowledge Agent to collect multimodal evidence via iterative searches, and leverages its reasoning capabilities to organize the information into citation-backed reports. It saves weeks of manual curation and provides a ready-to-use foundation for proposals, publications, or experimental design.

-   The ***In Silico* Research Agent facilitates the automated replication** of published studies by coordinating other agents. It can also generate a \`reproduce.sh\` script for one-command workflow re-execution from a clean environment, ensuring scientific reproducibility. Beyond replication, it supports exploratory analysis—researchers can modify datasets, parameters, or species to validate findings or explore new hypotheses, serving as both a replication engine and a hypothesis-testing platform.

-   The **Gene Network Agent** accepts user-defined gene lists to identify interaction partners, regulatory relationships, and functional associations. It synthesizes this information into coherent networks (e.g., hormone–gene–phenotype maps), enabling on-demand candidate gene network construction to help uncover biological pathways and link molecular interactions to phenotypes.

-   The **Brief Gene Agent** creates a rapid, citation-backed orientation for a target gene. It summarizes known functions, key evidence, and practical research leads when you need a focused starting point before commissioning a full gene report.

-   The **Deep Genome Agent** generates in-depth functional summaries for target genes by integrating literature, multi-omics data, and network information. Its final output is a gene-focused review report covering gene function, regulation, known variants, and potential breeding applications—serving as a one-stop reference for researchers.

-   The **Digital Design Agent** leverages the other agents for allele and protein engineering. Via natural language queries, it supports protein sequence modification and gene promoter optimization, predicts beneficial mutations, and generates protein variants with enhanced traits. It bridges computational design and experimental validation to accelerate synthetic biology, functional genomics, and crop improvement.

### Choosing the Right Input

**Best starting input and attachment guidance:**

-   **Chat Agent:** A specific research question with species and experimental context. Optional supported documents or images can provide context.
-   **Knowledge Agent:** A literature question, keywords, date range, and evidence scope. Optional supported documents can narrow the evidence set.
-   **Data Agent:** Species, gene or other entity identifiers, and the fields or relationship you need. It queries the integrated biological database; an uploaded spreadsheet is not required.
-   **Analyst Agent:** Analysis objective, data type, species, and a description or location for each dataset. Use only dataset controls explicitly offered by this agent.
-   **Review Agent:** Review topic, scope, species, date range, and desired report emphasis. Optional supported documents can seed the review.
-   ***In Silico* Research Agent:** Paper or hypothesis to reproduce, expected outcome, and dataset descriptions or locations. Use only dataset controls explicitly offered by this agent.
-   **Gene Network Agent:** Gene list, species, and optional trait or phenotype identifier. State the meaning of each list or dataset when prompted.
-   **Brief Gene Agent:** Gene identifier, species, and the aspect you want summarized. Optional supported documents can add local evidence.
-   **Deep Genome Agent:** Gene identifier and species, plus any requested functional or breeding focus. It uses integrated literature and multi-omics evidence.
-   **Digital Design Agent:** Target gene or protein sequence, design objective, and experimental constraints. Use only sequence or dataset controls explicitly offered by this agent.

General chat attachments currently support PDF, Word, Excel, PowerPoint, TXT, and PNG files, up to 10 files, 25 MB per file, and 50 MB in total. CSV is not a universal chat attachment format: use CSV only when an agent-specific dataset control explicitly advertises it.`,
      },
      resources: {
        heading: "4. What resources does Phytomni integrate?",
        body: `-   A **Knowledge Base** comprising over 4 million full-text agriculture and plant biology research papers published from 1900-2025, along with over 27 million abstracts and nearly 200,000 patents.
-   A **Biological Database** covering 65 plant species (including rice, maize, wheat, soybean, *Arabidopsis*, etc.) and 14 omics methods (e.g., genomics, transcriptomics, epigenomics, phenomics, etc.).
-   A **Bioinformatics Toolkit** containing 125 total bioinformatic tools, including 25 models and 100 command-line tools, encompassing a variety of biological scenarios.`,
      },
      limitations: {
        heading: "5. Limitations and Best Practices",
        body: `-   **Experimental Validation is Essential:** While Phytomni provides powerful *in silico* predictions, its outputs may contain theoretical gaps or require real-world context. Validating its recommendations via experiments is crucial to guarantee their reliability in practical scenarios.
-   **Iterative Refinement is Key:** For complex tasks, refine your queries, input parameters, or prompts based on initial results and feedback to gradually enhance the relevance and quality of the outputs.
-   **Provide Specific Context:** Furnish detailed context (e.g., task objectives, species, experimental conditions, background) to help the AI understand your intent clearly, minimizing ambiguities and improving response accuracy.`,
      },
    },
  },
};
