// English language pack.
export default {
  // Common parts
  common: {
    confirm: "Confirm",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    failed: "Failed",
    warning: "Warning",
    loading: "Loading",
    noData: "No Data",
    save: "Save",
    reset: "Reset",
    back: "Back",
    close: "Close",
    view: "View",
    index: "No.",
    operation: "Operation",
    running: "Running",
    finished: "Finished",
    Tip: "(Generated by AI)",
    aiDisclaimer: "Generated by AI. Please exercise discretion.",
    followSystem: "Follow system",
    opFailedRetry: "Operation failed, please try again",
    renamedSuccess: "Renamed successfully",
    renameFailedRetry: "Rename failed, please try again",
    deletedSuccess: "Deleted successfully",
    deleteFailedRetry: "Delete failed, please try again",
    refreshedSuccess: "Refreshed successfully",
    refreshFailed: "Refresh failed",
    refreshFailedRetry: "Refresh failed, please try again",
    userAddedSuccess: "User added successfully",
    userUpdatedSuccess: "User updated successfully",
    registrationSuccess: "Registration successful",
    sessionExpired: "Your session has expired, please log in again",
    notice: "Notice",
  },

  // Error pages
  errorPage: {
    back: "Back",
    goHome: "Back to Home",
    e401Title: "401 Error!",
    e401NoAccess: "You do not have access permission!",
    e401Detail:
      "Sorry, you do not have access permission. Please do not perform illegal operations. You can return to the home page.",
    e404Title: "404 Error!",
    e404NotFound: "Page not found!",
    e404Detail:
      "Sorry, the page you are looking for does not exist. Try checking the URL for errors, then press the refresh button on your browser or try to find something else in our application.",
  },

  // App information
  app: {
    title: "Phytomni",
  },

  // Interactive Tutorial
  tutorial: {
    step1: {
      title: "Welcome to Phytomni!",
      content:
        'First, let\'s get to know the navigation. Quick access to functions: "Start New" initiates a brand-new task, "Deep Genome Database" allows you to view gene information, "Favorites" is for collecting frequently-used content, and there are also historical interactions categorized by time to help you efficiently find past records.',
    },
    step2: {
      title: "Try a starter prompt",
      content:
        "These suggestion cards above the input are starter prompts. Click one to fill the composer with an example question.",
    },
    step3: {
      title: "Conversation Window",
      content:
        'This is the "window" for communicating with Phytomni. You can directly enter questions, or choose different intelligent assistants such as "ChatAgent" and "KnowledgeAgent" by yourself. Try clicking the input box. Are you ready to start exploring?',
    },
    nextStep: "Next Step",
    prevStep: "Previous",
    complete: "Complete",
    startTutorial: "Start Tutorial",
    navigationHint:
      "💡 Tip: Use ← → arrow keys or spacebar to navigate, ESC to exit",
  },

  // Menu
  menu: {
    deepGenome: "Deep Genome Database",
    favorites: "Favorites",
    feedback: "Feedback",
    userList: "User List",
    logList: "System Monitor",
    permissionManage: "Permissions",
    taskManager: "Task Management",
    globalConfig: "Global Policy Config",
    adminManagement: "Admin Management",
  },

  // Error codes
  errorCode: {
    401: "Authentication failed, unable to access system resources",
    403: "Current operation is not authorized",
    404: "Requested resource does not exist",
    default: "Unknown system error, please report to administrator",
  },

  // Request layer (used by axios interceptor)
  request: {
    sessionExpired: "Your session has expired. Please log in again.",
    sessionInvalid: "Invalid or expired session. Please log in again.",
    confirmButtonText: "OK",
    networkError: "Backend connection failed",
    requestTimeout: "Request timed out",
    httpStatusError: "Server error ({code})",
  },

  // Change password
  changePassword: {
    usernamePlaceholder: "Please enter username",
    oldPassword: "Old Password",
    oldPasswordPlaceholder: "Please enter old password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Please enter new password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Please confirm new password",
    confirm: "Confirm Change",
    usernameRequired: "Please enter username",
    oldPasswordRequired: "Please enter old password",
    newPasswordRequired: "Please enter new password",
    confirmPasswordRequired: "Please confirm new password",
    passwordMinLength: "Password must be at least 6 characters",
    passwordMinLength8: "Password must be at least 8 characters",
    passwordNeedUppercase: "Password must contain uppercase letters",
    passwordNeedLowercase: "Password must contain lowercase letters",
    passwordNeedNumber: "Password must contain numbers",
    passwordNeedSpecial: "Password must contain special characters",
    passwordSame: "New password cannot be the same as old password",
    passwordMismatch: "Passwords do not match",
    formValidationFailed: "Please check the form for errors",
    passwordChangeSuccess: "Password changed successfully",
    passwordChangeFailed: "Failed to change password",
    passwordChangeRetry: "Failed to change password, please try again later",
  },

  // Login module
  login: {
    title: "Phytomni",
    subtitle: "A multi-agent system for scientific discovery and plant design",
    email: "Email",
    emailPlaceholder: "Please enter your email address",
    password: "Password",
    passwordPlaceholder: "8-16 characters, case sensitive",
    forgotPassword: "Forgot password?",
    loginButton: "Login",
    noAccount: "No account?",
    register: "Register",
    login: "Login",
    loginSuccess: "Login successful",
    loginFailed: "Login failed",
    registerFailed: "Registration failed",
    passwordWarningTitle: "Password Security Notice",
    accountLockedTitle: "Account Locked",
    firstLoginTitle: "First Login Notice",
    firstLoginMessage:
      "This is your first login. For security purposes, please change your initial password.",
    firstLoginEnforceTitle: "Password Change Required",
    firstLoginEnforceMessage:
      "You must change your initial password before accessing other pages.",
    validation: {
      emailRequired: "Please enter your email",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter your password",
      passwordLength: "Password must be 8-16 characters long",
    },
    agreement: {
      prefix:
        "Registering and logging in means you have read and agreed to our",
      terms: "User Agreement",
      and: "and",
      privacy: "Privacy Policy",
    },
  },

  // Register module
  register: {
    title: "Create Account",
    subtitle: "Create your Phytomni account",
    email: "Email",
    emailPlaceholder: "Please enter your email address",
    password: "Password",
    passwordPlaceholder: "Please enter your password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Please confirm your password",
    registerButton: "Register",
    haveAccount: "Already have an account?",
    login: "Login",
    agreement: {
      prefix: "By registering, you agree to our",
      terms: "Terms of Service",
      and: "and",
      privacy: "Privacy Policy",
      checkboxLabel:
        "I have read and agree to the Terms of Service and Privacy Policy",
      checkboxRequired:
        "Please agree to the Terms of Service and Privacy Policy",
    },
    validation: {
      emailRequired: "Please enter your email address",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter your password",
      passwordMinLength8: "@:changePassword.passwordMinLength8",
      passwordMaxLength16: "Password must not exceed 16 characters",
      passwordNeedUppercase: "@:changePassword.passwordNeedUppercase",
      passwordNeedLowercase: "@:changePassword.passwordNeedLowercase",
      passwordNeedNumber: "@:changePassword.passwordNeedNumber",
      passwordNeedSpecial: "Password must contain special characters",
      confirmPasswordRequired: "Please confirm your password",
      confirmPasswordMismatch: "Passwords do not match",
      formValidationFailed: "Please check the form for errors",
    },
  },

  legal: {
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    icpFiling: "京ICP备07026971号-9",
    versionLabel: "Version",
    effectiveLabel: "Effective date",
    draftBanner:
      "Draft pending review by Biotechnology Research Institute, CAAS. Not a final legal instrument.",
    loadError: "Unable to load this document. Please try again later.",
  },

  // Forgot password module
  forgotPassword: {
    title: "Forgot Password",
    backToLogin: "Back to Login",
    unavailableTitle: "Password Reset Not Yet Available",
    unavailableMessage:
      "This feature is under development. Please contact your system administrator to reset your password.",
  },

  // User management
  user: {
    list: "User List",
    listTitle: "User List",
    passwordEditPlaceholder: "Leave blank to keep the password unchanged",
    unnamedUser: "Unnamed user",
    add: "Add User",
    edit: "Edit User",
    username: "Username",
    password: "Password",
    role: "Role",
    roleSelect: "Please select a role",
    admin: "Administrator",
    addFailed: "Add failed",
    editFailed: "Edit failed",
    detail: "User Details",
    changePassword: "Change Password",
    feedback: "Feedback",
    logout: "Logout",
    history: "History",
    profile: "Profile",
    cloudStorage: "Cloud Storage",
    systemMonitor: "System Monitor",
    globalConfig: "Global Policy Config",
    adminManagement: "Admin Management",
    unlock: "Unlock",
    unlockConfirmTitle: "Unlock User",
    unlockConfirmMessage: "Are you sure you want to unlock user {email}?",
    unlockSuccess: "User unlocked successfully",
    unlockFailed: "Failed to unlock user",
    phone: "Phone",
    phonePlaceholder: "Please enter phone number",
    organization: "Organization",
    organizationPlaceholder: "Please enter organization",
    position: "Position",
    positionPlaceholder: "Please enter position",
    lastLoginAt: "Last Login",
    notLoggedIn: "Not logged in",
    chatLimit: "Chat Limit",
    chatLimitPlaceholder: "Please enter chat limit",
    unlimited: "Unlimited",
    validation: {
      emailRequired: "Please enter username",
      emailFormat: "Please enter a valid email address",
      passwordRequired: "Please enter password",
      passwordLength: "Length must be between 8 and 16 characters",
      passwordMinLength8: "@:changePassword.passwordMinLength8",
      passwordMaxLength16: "Password must not exceed 16 characters",
      passwordNeedUppercase: "@:changePassword.passwordNeedUppercase",
      passwordNeedLowercase: "@:changePassword.passwordNeedLowercase",
      passwordNeedNumber: "@:changePassword.passwordNeedNumber",
      passwordNeedSpecial: "Password must contain special characters",
      roleRequired: "Please select a role",
      formValidationFailed: "Please check the form for errors",
    },
  },

  // Gene display
  gene: {
    notFound: "Gene details not found",
    searchPlaceholder: "Please enter species or gene to search",
    getFailed: "Failed to get gene details",
    geneName: "File Name",
    biocode: "species",
    geneId: "Gene ID",
    logs: {
      fetchDataFailed: "Failed to fetch data:",
      fetchDetailFailed: "Failed to fetch gene details:",
    },
  },

  // Chat module
  chat: {
    untitledConversation: "New chat",
    conversationTitle: "Conversation title",
    appTitle: "Phytomni",
    welcome: "Welcome, please enter your question directly",
    inputPlaceholder: "Please enter your question...",
    send: "Send",
    newChat: "Start New",
    exploreAgent: "Explore Agents",
    agentsArchitectureTitle: "Phytomni Agent Architecture",
    agentsArchitectureAlt: "Phytomni agent architecture diagram",
    deepGenome: "Deep Genome Database",
    useTool: "Use Tool",
    stepResult: "Step Result",
    resultImageAlt: "Result image {index}",
    sendFailed: "Failed to send message, please try again later.",
    timeoutFailed: "The request timed out. Try narrowing your query or retry later.",
    sendAriaLabel: "Send",
    abortAriaLabel: "Stop answering",
    eta: {
      fast: "Usually 5–30s",
      medium: "Usually 1–3 min",
      slow: "Usually 3–10 min",
    },
    generationStopped: "Generation stopped",
    relatedDocuments: "Reference Material",
    welcomeTitle: "Hi, I'm Phytomni. Great to meet you!",
    mode: {
      instant: "Instant",
      expert: "Expert",
      comingSoon: "Coming soon",
    },
    tools: {
      generic: "Calling a tool",
      knowledge_search: "Searching literature",
    },
    steps: {
      retrieving: "Retrieving",
    },
    toolHits: "{count} hits",
    streamInterrupted: "Connection interrupted, please retry.",
    a2ui: {
      confirm: "Confirm",
      cancel: "Cancel",
      submit: "Submit",
      expired: "This prompt is no longer active.",
      failed: "This prompt failed. Please retry the question.",
      locked: "Submitted",
    },
    reasoning: { show: "Show reasoning", hide: "Hide reasoning" },
    welcomeSubtitle:
      "I can retrieve information and perform automated analysis for you. Feel free to give me your tasks.",
    starter: {
      title: "Try one of these",
      geneLabel: "Query a gene",
      geneDesc: "Function and homologs of a gene",
      genePrompt: "Tell me about the function and homologs of gene Os01g0177400",
      speciesLabel: "Explore a species",
      speciesDesc: "Key genes and pathways of a species",
      speciesPrompt: "Which key genes are involved in drought resistance in rice?",
      deepGenomeLabel: "Deep genome analysis",
      deepGenomeDesc: "Run a deep genome report on a gene",
      deepGenomePrompt: "Run a deep genome analysis for gene Os01g0177400",
    },
    inputPlaceholderTip: "Please enter your question",
    uploadFile:
      "Support file upload(max 10, accept .pdf,.doc,.xlsx,.ppt,.txt,.png)",
    timeGroup: {
      today: "Today",
      yesterday: "Yesterday",
      week: "Within 7 Days",
      older: "Older Than a Week",
    },
    agents: {
      chatAgent:
        "Your AI assistant for answering plant research questions in natural language.",
      knowledgeAgent: "Expert-curated plant knowledge at your fingertips.",
      dataAgent: "Handles and optimizes plant datasets for research.",
      analystAgent: "Transforms raw data into meaningful plant insights.",
      reviewAgent:
        "Generates AI-powered literature reviews for agricultural research.",
      briefGeneAgent:
        "Creates rapid gene-function briefs and research leads.",
      deepGenomeAgent: "Decodes plant genomes for smarter breeding strategies.",
      inSilicoResearchAgent:
        "Simulates plant experiments digitally to accelerate discovery.",
      geneNetworkAgent:
        "Decodes gene regulatory networks to uncover key pathways for crop stress resistance and yield.",
      digitalDesignAgent:
        "AI-driven design of gene promoters and protein structures for synthetic biology and molecular breeding.",
    },
    logs: {
      sendMessageFailed: "Failed to send message:",
    },
    downloadURL: "Download link",
    copySuccess: "Copied successfully",
    copyFailed: "Copy failed",
    pendingWriteFailed: "Session backup failed, sending unaffected",
    icpAriaLabel: "MIIT ICP filing",
    copy: "Copy",
    ladingInner:
      "Processing your request: retrieving data, analyzing information, and generating a response. Please wait",
    footer: "Generated by AI. Please carefully examine.",
    followUpQuestions: "Question Suggestions:",
    more: "More",
    actions: {
      rename: "Rename",
      favorite: "Favorite",
      unfavorite: "Unfavorite",
      delete: "Delete",
      deleteConfirm: "Confirm Delete",
      deleteWarning:
        "Are you sure you want to delete this conversation? This action cannot be undone.",
      enterNewTitle: "Please enter a new title",
      like: "Like",
      undoLike: "Undo like",
      dislike: "Dislike",
      undoDislike: "Undo dislike",
    },
    favorites: "Favorites",
    noFavorites: "No Favorites",
    noFavoritesDescription:
      "You haven't favorited any conversations yet. Start chatting and favorite the content you like",
    startChat: "Start Chat",
    favoritesCount: "{count} Favorites",
    openChat: "Open Chat",
    refresh: "Refresh",
    loveThis: "Love this",
    needsImprovement: "Needs Improvement",
    hideLog: "Hide Log",
    showLog: "View Log",
    downloadFile: "Download File",
    testParallel: "Test parallel chats",
    refreshReply: "Refresh reply",
    abortTooltip: "Abort answer",
    loadingAgentPerms: "Loading agent permissions...",
    agentPicker: {
      loading: "Loading agent permissions...",
      empty: "No agents available for your account",
      searchPlaceholder: "Search agents…",
      remove: "Remove {agent}",
    },
    log: {
      replyContent: "Reply Content",
      execLog: "Execution Log (ID: {id})",
      updateLog: "Update Log",
      loading: "Loading logs...",
      contentColumn: "Log Content",
      noData: "No log data",
    },
    logUpdatedSuccess: "Log updated successfully",
    logUpdateFailed: "Failed to update log",
    logUpdateFailedRetry: "Failed to update log, please try again",
    liked: "Liked",
    disliked: "Disliked",
    cancelled: "Cancelled",
    printFailed: "Print failed",
    transferCancel: "Cancel",
    transferEta: "About {seconds}s left",
    transferSize: "{loaded} / {total}",
    downloadCancelled: "Download cancelled",
    downloadError:
      "An error occurred while downloading, please contact the administrator!",
  },

  // History module
  history: {
    noHistory: "No history yet",
    noHistoryDescription:
      "You don't have any chat history yet. Start chatting and view your conversation history",
    historyCount: "{count} history records",
    loadFailed: "Failed to load history",
  },

  // Favorites module
  favorites: {
    loadFailed: "Failed to load favorites",
    removedSuccess: "Removed from favorites",
    removeFailed: "Failed to remove favorite",
    addedSuccess: "Added to favorites",
  },

  // Profile management module
  profile: {
    title: "Profile Management",
    description:
      "Manage your personal information, account security and usage statistics",
    basicInfo: {
      title: "Basic Information",
      username: "Username",
      email: "Email",
      phone: "Phone",
      organization: "Organization",
      position: "Position",
    },
    security: {
      title: "Account Security",
      password: "Login Password",
      passwordDescription:
        "Change your password regularly to ensure account security",
      changePassword: "Change Password",
      permission: "User Permission",
      permissionDescription: "Current account permission level",
      oldPassword: "Old Password",
      oldPasswordPlaceholder: "@:changePassword.oldPasswordPlaceholder",
      newPassword: "New Password",
      newPasswordPlaceholder: "@:changePassword.newPasswordPlaceholder",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "@:changePassword.confirmPasswordPlaceholder",
    },
    usage: {
      title: "Usage Statistics",
      totalChats: "Total Chats",
      lastLogin: "Last Login",
    },
    passwordChangeSuccess: "Password changed successfully",
    passwordChangeFailed: "Failed to change password, please try again",
    userInfoNotFound: "User information not found",
    fetchUserInfoFailed: "Failed to fetch user information",
    fetchUserInfoError: "Failed to fetch user information",
  },

  // Cloud storage module
  cloudStorage: {
    title: "Cloud Drive (Beta)",
    description:
      "This is a simplified preview. Some features are still under construction.",
    tryDemo: "Try Demo",
  },

  // Log management
  log: {
    list: "Log List",
  },

  // Permission management
  permission: {
    title: "Permissions",
  },

  // Task management
  taskManager: {
    question: "Question",
    status: "Status",
    updated_at: "Updated Time",
    downloadURL: "Download",
    dialogue_link: "Link",
    getFailed: "Failed to get list",
    logs: {
      fetchDataFailed: "Failed to obtain data list",
    },
    operate: "Operate",
  },

  // User Feedback
  feedback: {
    placeholder:
      "Please describe your questions, suggestions, or feedback in detail...",
    submit: "Submit Feedback",
    submitSuccess:
      "Feedback submitted successfully. Thank you for your valuable input!",
    submitFailed: "Submission failed, please try again",
  },

  // Global Policy Configuration
  globalConfig: {
    description: "Manage system global policies and security configurations",
    systemSettings: "System Settings",
    basicSettings: "Basic Configuration",
    securitySettings: "Security Policy",
    featureSettings: "Feature Configuration",
    systemName: "System Name",
    systemNamePlaceholder: "Please enter system name",
    maxFileSize: "Max File Size",
    sessionTimeout: "Session Timeout",
    minutes: "minutes",
    passwordPolicy: "Password Policy",
    requireUppercase: "Require Uppercase",
    requireLowercase: "Require Lowercase",
    requireNumbers: "Require Numbers",
    requireSymbols: "Require Symbols",
    loginAttempts: "Max Login Attempts",
    attempts: "attempts",
    ipWhitelist: "IP Whitelist",
    ipWhitelistPlaceholder: "Please enter IP addresses, one per line",
    enableRegistration: "Enable User Registration",
    enableFileUpload: "Enable File Upload",
    enableChatHistory: "Enable Chat History",
    maxChatHistory: "Max Chat History Records",
    records: "records",
    testConfig: "Test Configuration",
    configHistory: "Configuration History",
    timestamp: "Timestamp",
    operator: "Operator",
    changes: "Changes",
    historyDetail: "History Detail",
    historyDetailContent: "Time: {time}\nOperator: {operator}\nChanges: {changes}",
    saveSuccess: "Configuration saved successfully",
    saveFailed: "Failed to save configuration",
    resetConfirm:
      "Are you sure you want to reset all configurations to default values?",
    resetSuccess: "Configuration reset successfully",
    testUnavailable: "Configuration test is not yet wired to the backend",
  },

  // Agent Pages
  agents: {
    analyst: {
      title: "Analyst Agent",
      subtitle:
        "Analysis Agent - Provides bioinformatics data analysis and interpretation services",
      taskCreated: "Task created successfully",
      downloadResults: "Download Analysis Results",
    },
    data: {
      title: "Data Agent",
      subtitle:
        "Data Agent - Provides multi-omics data analysis and processing services",
    },
    briefGene: {
      title: "Brief Gene Agent",
      subtitle:
        "Brief Gene Agent - Provides rapid gene-function briefs and research leads",
    },
    knowledge: {
      title: "Knowledge Agent",
      subtitle:
        "Knowledge Agent - Provides bioinformatics knowledge query and analysis services",
    },
    deepGenome: {
      title: "Deep Genome Agent",
      subtitle:
        "Deep Genome Agent - Provides in-depth analysis services for species and genes",
      taskCreated: "Task created successfully",
      downloadPDF: "Download PDF",
      downloadMD: "Download Markdown",
      imageViewerTitle: "Image Viewer",
    },
    geneNetwork: {
      title: "Gene Network Agent",
      subtitle:
        "Gene Network Agent - Provides gene network analysis and phenotype trait association services",
      taskCreated: "Task created successfully",
      downloadResults: "Download Analysis Results",
      downloading: "Downloading...",
      volumeProgress: "Downloading volume {current}/{total}",
    },
    digitalDesign: {
      title: "Digital Design Agent",
      subtitle:
        "Digital Design Agent - Provides protein structure prediction and design services based on gene IDs",
      taskCreated: "Task created successfully",
      downloadResults: "Download Analysis Results",
    },
  },

  // Help Center
  help: {
    title: "Help Center",
    tableOfContents: "Table of Contents",
    goBackTokenExpired: "Login expired, please log in again",
    goBackFailed: "Failed to go back to previous page",
    toc: {
      whatIs: "What is Phytomni?",
      gettingStarted: "Getting Started",
      howItWorks: "How does Phytomni work?",
      resources: "What resources does Phytomni integrate?",
      limitations: "Limitations and Best Practices",
    },
    doc: {
      whatIs: {
        heading: "1. What is Phytomni?",
        body: `Phytomni is an intelligent agentic AI system for scientific discovery and design in plant research, which can assist researchers to significantly accelerate scientific discovery, including:

-   Answering diverse scientific questions directly with natural language queries;
-   Unlocking insights from over 4 million full-text scientific articles, extracting reliable insights, and providing direct answers with source references;
-   Integrating and analyzing 14 types of omics datasets covering 65 plant species to generate precise digital insights;
-   Accepting user-submitted data and task requirements, and autonomously planning and executing bioinformatics analyses;

Building upon these core capabilities, Phytomni can perform complex research tasks, including but not limited to:

-   Automated integration of literature and generation of domain review reports;
-   Integrating multi-dimensional information to analyze gene function and write professional reports;
-   Automating key steps in the reproduction of published scientific studies;
-   Discovering new biological pathways (such as hormone-gene-phenotype network analysis);
-   Designing and optimizing alleles and proteins (including gene promoters and protein engineering);
-   **... ...**`,
      },
      gettingStarted: {
        heading: "2. Getting Started: How to Use Phytomni",
        body: `Using Phytomni is a conversational, task-oriented process. Follow these simple steps to begin your research:

### Step 1: Formulate and Submit Your Query

To start using Phytomni, the first step is to clearly formulate your research query. You need to select the corresponding **AGENT** button and describe your specific objectives as precisely as possible—whether they involve literature retrieval, data extraction, or analytical tasks. Clear and detailed instructions will ensure that Phytomni accurately captures your research needs and delivers high-quality results.

### Step 2: Monitor and Manage Your Task

After submitting your query, you can monitor its progress in real time through the **Task Management** module. This module provides an overview of your submitted tasks, including the original problem, task status, and the most recent update time.

### Step 3: Review and Explore Results

Once the task is completed, you will be able to review the results directly in the system. For example, when exploring specific genes, the Deep Genome Database module offers a comprehensive, integrated view of the target gene, including basic information, literature summaries, interaction networks, and expression heatmaps. You can download your results for further use or export them into different formats. To facilitate long-term research, completed tasks can also be saved as favourites, allowing you to easily revisit and reuse them whenever needed.`,
      },
      howItWorks: {
        heading:
          "3. How does Phytomni work? Understanding the Architecture and Capabilities",
        body: `### The Dual-LLM Core

The **Phytomni-Hub** module serves as the central intelligence for the entire system. This module integrates two domain-specific LLMs—**Phyto-Chatbot** and **Phyto-Reasoner**—both of which were pre-trained on knowledge from Phytomni's resource modules and fine-tuned with high-quality data. **Phyto-Chatbot** is capable of intent recognition and initiating data searches, while **Phyto-Reasoner** is responsible for reasoning, planning, and knowledge synthesis. The two work synergistically to support automated bioinformatic operations.

### A Team of AI Agents and Their Applications

Phytomni accomplishes tasks by orchestrating a team of specialized agents. Here's what each agent does and how you can use them:

-   The **Chat Agent** is your primary conversational interface with Phytomni. It answers various research questions in natural language, explains complex biological concepts, and provides guidance on experimental design or data analysis. This agent enables researchers to quickly gain actionable insights without having to manually navigate multiple databases.

-   The **Knowledge Agent** is built on a century-spanning agricultural knowledge base, integrating over 4 million full-text articles, 27 million abstracts, and nearly 200,000 structured patents. It supports natural language queries to retrieve and extract full-text information, generating evidence-based answers with complete source references—turning fragmented plant research into an accessible, authoritative discovery foundation.

-   The **Data Agent** is powered by a multi-omics database covering 65 plant species and 14 omics data types. It unifies 21 identifier types, corrects errors, removes redundancies, and standardizes entries. It intelligently translates your natural language query into a precise database query (SQL) to extract, cross-link, and visualize gene-centric or system-level biological data, enabling seamless exploration of plant genomes, expression profiles, and protein interactions.

-   The **Analyst Agent** functions like an automated bioinformatician, integrating a library of over 120 curated bioinformatics tools. It plans and executes complex tasks (such as sequence analysis or gene expression profiling) and embeds expert-validated pipelines into a user-friendly interface, enabling end-to-end multi-omics analyses without manual software installation or configuration.

-   The **Review Agent** automatically generates comprehensive literature reviews on targeted research topics. It interprets user queries to build a review plan, uses the Knowledge Agent to collect multimodal evidence via iterative searches, and leverages its reasoning capabilities to organize the information into citation-backed reports. It saves weeks of manual curation and provides a ready-to-use foundation for proposals, publications, or experimental design.

-   The ***In Silico* Research Agent facilitates the automated replication** of published studies by coordinating other agents. It can also generate a \`reproduce.sh\` script for one-command workflow re-execution from a clean environment, ensuring scientific reproducibility. Beyond replication, it supports exploratory analysis—researchers can modify datasets, parameters, or species to validate findings or explore new hypotheses, serving as both a replication engine and a hypothesis-testing platform.

-   The **Gene Network Agent** accepts user-defined gene lists to identify interaction partners, regulatory relationships, and functional associations. It synthesizes this information into coherent networks (e.g., hormone–gene–phenotype maps), enabling on-demand candidate gene network construction to help uncover biological pathways and link molecular interactions to phenotypes.

-   The **Deep Genome Agent** generates in-depth functional summaries for target genes by integrating literature, multi-omics data, and network information. Its final output is a gene-focused review report covering gene function, regulation, known variants, and potential breeding applications—serving as a one-stop reference for researchers.

-   The **Digital Design Agent** leverages the other agents for allele and protein engineering. Via natural language queries, it supports protein sequence modification and gene promoter optimization, predicts beneficial mutations, and generates protein variants with enhanced traits. It bridges computational design and experimental validation to accelerate synthetic biology, functional genomics, and crop improvement.`,
      },
      resources: {
        heading: "4. What resources does Phytomni integrate?",
        body: `-   A **Knowledge Base** comprising over 4 million full-text agriculture and plant biology research papers published from 1900-2025, along with over 27 million abstracts and nearly 200,000 patents.
-   A **Biological Database** covering 65 plant species (including rice, maize, wheat, soybean, *Arabidopsis*, etc.) and 14 omics methods (e.g., genomics, transcriptomics, epigenomics, phenomics, etc.).
-   A **Bioinformatics Toolkit** containing 125 total bioinformatic tools, including 25 models and 100 command-line tools, encompassing a variety of biological scenarios.`,
      },
      limitations: {
        heading: "5. Limitations and Best Practices",
        body: `-   **Experimental Validation is Essential:** While Phytomni provides powerful *in silico* predictions, its outputs may contain theoretical gaps or require real-world context. Validating its recommendations via experiments is crucial to guarantee their reliability in practical scenarios.
-   **Iterative Refinement is Key:** For complex tasks, refine your queries, input parameters, or prompts based on initial results and feedback to gradually enhance the relevance and quality of the outputs.
-   **Provide Specific Context:** Furnish detailed context (e.g., task objectives, species, experimental conditions, background) to help the AI understand your intent clearly, minimizing ambiguities and improving response accuracy.`,
      },
    },
  },
};
